# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

pokemon_list = [
  [ 1, "Bulbasaur", "grass", "poison" ],
  [ 2, "Ivysaur", "grass", "poison" ],
  [ 3, "Venusaur", "grass", "poison" ],
  # [ 3, "Mega Venusaur", "grass", "poison" ],
  [ 4, "Charmander", "fire", "N/A" ],
  [ 5, "Charmeleon", "fire", "N/A" ],
  [ 6, "Charizard", "fire", "flying" ],
  # [ 6, "Mega Charizard X", "fire", "dragon" ],
  # [ 6, "Mega Charizard Y", "fire", "flying" ],
  [ 7, "Squirtle", "water", "N/A" ],
  [ 8, "Wartortle", "water", "N/A" ],
  [ 9, "Blastoise", "water", "N/A" ],
  # [ 9, "Mega Blastoise", "water", "N/A" ],
  [ 10, "Caterpie", "bug", "N/A" ],
  [ 11, "Metapod", "bug", "N/A" ],
  [ 12, "Butterfree", "bug", "flying" ],
  [ 13, "Weedle", "bug", "poison" ],
  [ 14, "Kakuna", "bug", "poison" ],
  [ 15, "Beedrill", "bug", "poison" ],
  # [ 15, "Mega Beedrill", "bug", "poison" ],
  [ 16, "Pidgey", "normal", "flying" ],
  [ 17, "Pidgeotto", "normal", "flying" ],
  [ 18, "Pidgeot", "normal", "flying" ],
  # [ 18, "Mega Pidgeot", "normal", "flying" ],
  [ 19, "Rattata", "normal", "N/A" ],
  # [ 19, "Alolan Rattata", "dark", "normal" ],
  [ 20, "Raticate", "normal", "N/A" ],
  # [ 20, "Alolan Raticate", "dark", "normal" ],
  [ 21, "Spearow", "normal", "flying" ],
  [ 22, "Fearow", "normal", "flying" ],
  [ 23, "Ekans", "poison", "N/A" ],
  [ 24, "Arbok", "poison", "N/A" ],
  [ 25, "Pikachu", "electric", "N/A" ],
  # [ 25, "Partner Pikachu", "electric", "N/A" ],
  [ 26, "Raichu", "electric", "N/A" ],
  # [ 26, "Alolan Raichu", "electric", "psychic" ],
  [ 27, "Sandshrew", "ground", "N/A" ],
  # [ 27, "Alolan Sandshrew", "ice", "steel" ],
  [ 28, "Sandslash", "ground", "N/A" ],
  # [ 28, "Alolan Sandslash", "ice", "steel" ],
  [ 29, "Nidoran♀", "poison", "N/A" ],
  [ 30, "Nidorina", "poison", "N/A" ],
  [ 31, "Nidoqueen", "poison", "ground" ],
  [ 32, "Nidoran♂", "poison", "N/A" ],
  [ 33, "Nidorino", "poison", "N/A" ],
  [ 34, "Nidoking", "poison", "ground" ],
  [ 35, "Clefairy", "fairy", "N/A" ],
  [ 36, "Clefable", "fairy", "N/A" ],
  [ 37, "Vulpix", "fire", "N/A" ],
  # [ 37, "Alolan Vulpix", "ice", "N/A" ],
  [ 38, "Ninetales", "fire", "N/A" ],
  # [ 38, "Alolan Ninetales", "ice", "fairy" ],
  [ 39, "Jigglypuff", "normal", "fairy" ],
  [ 40, "Wigglytuff", "normal", "fairy" ],
  [ 41, "Zubat", "poison", "flying" ],
  [ 42, "Golbat", "poison", "flying" ],
  [ 43, "Oddish", "grass", "poison" ],
  [ 44, "Gloom", "grass", "poison" ],
  [ 45, "Vileplume", "grass", "poison" ],
  [ 46, "Paras", "bug", "grass" ],
  [ 47, "Parasect", "bug", "grass" ],
  [ 48, "Venonat", "bug", "poison" ],
  [ 49, "Venomoth", "bug", "poison" ],
  [ 50, "Diglett", "ground", "N/A" ],
  # [ 50, "Alolan Diglett", "ground", "steel" ],
  [ 51, "Dugtrio", "ground", "N/A" ],
  # [ 51, "Alolan Dugtrio", "ground", "steel" ],
  [ 52, "Meowth", "normal", "N/A" ],
  # [ 52, "Alolan Meowth", "dark", "N/A" ],
  [ 53, "Persian", "normal", "N/A" ],
  # [ 53, "Alolan Persian", "dark", "N/A" ],
  [ 54, "Psyduck", "water", "N/A" ],
  [ 55, "Golduck", "water", "N/A" ],
  [ 56, "Mankey", "fighting", "N/A" ],
  [ 57, "Primeape", "fighting", "N/A" ],
  [ 58, "Growlithe", "fire", "N/A" ],
  [ 59, "Arcanine", "fire", "N/A" ],
  [ 60, "Poliwag", "water", "N/A" ],
  [ 61, "Poliwhirl", "water", "N/A" ],
  [ 62, "Poliwrath", "water", "fighting" ],
  [ 63, "Abra", "psychic", "N/A" ],
  [ 64, "Kadabra", "psychic", "N/A" ],
  [ 65, "Alakazam", "psychic", "N/A" ],
  # [ 65, "Mega Alakazam", "psychic", "N/A" ],
  [ 66, "Machop", "fighting", "N/A" ],
  [ 67, "Machoke", "fighting", "N/A" ],
  [ 68, "Machamp", "fighting", "N/A" ],
  [ 69, "Bellsprout", "grass", "poison" ],
  [ 70, "Weepinbell", "grass", "poison" ],
  [ 71, "Victreebel", "grass", "poison" ],
  [ 72, "Tentacool", "water", "poison" ],
  [ 73, "Tentacruel", "water", "poison" ],
  [ 74, "Geodude", "rock", "ground" ],
  # [ 74, "Alolan Geodude", "rock", "electric" ],
  [ 75, "Graveler", "rock", "ground" ],
  # [ 75, "Alolan Graveler", "rock", "electric" ],
  [ 76, "Golem", "rock", "ground" ],
  # [ 76, "Alolan Golem", "rock", "electric" ],
  [ 77, "Ponyta", "fire", "N/A" ],
  [ 78, "Rapidash", "fire", "N/A" ],
  [ 79, "Slowpoke", "water", "psychic" ],
  [ 80, "Slowbro", "water", "psychic" ],
  # [ 80, "Mega Slowbro", "water", "psychic" ],
  [ 81, "Magnemite", "electric", "steel" ],
  [ 82, "Magneton", "electric", "steel" ],
  [ 83, "Farfetch'd", "normal", "flying" ],
  [ 84, "Doduo", "normal", "flying" ],
  [ 85, "Dodrio", "normal", "flying" ],
  [ 86, "Seel", "water", "N/A" ],
  [ 87, "Dewgong", "water", "ice" ],
  [ 88, "Grimer", "poison", "N/A" ],
  # [ 88, "Alolan Grimer", "poison", "dark" ],
  [ 89, "Muk", "poison", "N/A" ],
  # [ 89, "Alolan Muk", "poison", "dark" ],
  [ 90, "Shellder", "water", "N/A" ],
  [ 91, "Cloyster", "water", "ice" ],
  [ 92, "Gastly", "ghost", "poison" ],
  [ 93, "Haunter", "ghost", "poison" ],
  [ 94, "Gengar", "ghost", "poison" ],
  # [ 94, "Mega Gengar", "ghost", "poison" ],
  [ 95, "Onix", "rock", "ground" ],
  [ 96, "Drowzee", "psychic", "N/A" ],
  [ 97, "Hypno", "psychic", "N/A" ],
  [ 98, "Krabby", "water", "N/A" ],
  [ 99, "Kingler", "water", "N/A" ],
  [ 100, "Voltorb", "electric", "N/A" ],
  [ 101, "Electrode", "electric", "N/A" ],
  [ 102, "Exeggcute", "grass", "psychic" ],
  [ 103, "Exeggutor", "grass", "psychic" ],
  # [ 103, "Alolan Exeggutor", "grass", "dragon" ],
  [ 104, "Cubone", "ground", "N/A" ],
  [ 105, "Marowak", "ground", "N/A" ],
  # [ 105, "Alolan Marowak", "fire", "ghost" ],
  [ 106, "Hitmonlee", "fighting", "N/A" ],
  [ 107, "Hitmonchan", "fighting", "N/A" ],
  [ 108, "Lickitung", "normal", "N/A" ],
  [ 109, "Koffing", "poison", "N/A" ],
  [ 110, "Weezing", "poison", "N/A" ],
  [ 111, "Rhyhorn", "ground", "rock" ],
  [ 112, "Rhydon", "ground", "rock" ],
  [ 113, "Chansey", "normal", "N/A" ],
  [ 114, "Tangela", "grass", "N/A" ],
  [ 115, "Kangaskhan", "normal", "N/A" ],
  # [ 115, "Mega Kangaskhan", "normal", "N/A" ],
  [ 116, "Horsea", "water", "N/A" ],
  [ 117, "Seadra", "water", "N/A" ],
  [ 118, "Goldeen", "water", "N/A" ],
  [ 119, "Seaking", "water", "N/A" ],
  [ 120, "Staryu", "water", "N/A" ],
  [ 121, "Starmie", "water", "psychic" ],
  [ 122, "Mr. Mime", "psychic", "fairy" ],
  [ 123, "Scyther", "bug", "flying" ],
  [ 124, "Jynx", "ice", "psychic" ],
  [ 125, "Electabuzz", "electric", "N/A" ],
  [ 126, "Magmar", "fire", "N/A" ],
  [ 127, "Pinsir", "bug", "N/A" ],
  # [ 127, "Mega Pinsir", "bug", "flying" ],
  [ 128, "Tauros", "normal", "N/A" ],
  [ 129, "Magikarp", "water", "N/A" ],
  [ 130, "Gyarados", "water", "flying" ],
  # [ 130, "Mega Gyarados", "water", "dark" ],
  [ 131, "Lapras", "water", "ice" ],
  [ 132, "Ditto", "normal", "N/A" ],
  [ 133, "Eevee", "normal", "N/A" ],
  # [ 133, "Partner Eevee", "normal", "N/A" ],
  [ 134, "Vaporeon", "water", "N/A" ],
  [ 135, "Jolteon", "electric", "N/A" ],
  [ 136, "Flareon", "fire", "N/A" ],
  [ 137, "Porygon", "normal", "N/A" ],
  [ 138, "Omanyte", "rock", "water" ],
  [ 139, "Omastar", "rock", "water" ],
  [ 140, "Kabuto", "rock", "water" ],
  [ 141, "Kabutops", "rock", "water" ],
  [ 142, "Aerodactyl", "rock", "flying" ],
  # [ 142, "Mega Aerodactyl", "rock", "flying" ],
  [ 143, "Snorlax", "normal", "N/A" ],
  [ 144, "Articuno", "ice", "flying" ],
  [ 145, "Zapdos", "electric", "flying" ],
  [ 146, "Moltres", "fire", "flying" ],
  [ 147, "Dratini", "dragon", "N/A" ],
  [ 148, "Dragonair", "dragon", "N/A" ],
  [ 149, "Dragonite", "dragon", "flying" ],
  [ 150, "Mewtwo", "psychic", "N/A" ],
  # [ 150, "Mega Mewtwo X", "psychic", "fighting" ],
  # [ 150, "Mega Mewtwo Y", "psychic", "N/A" ],
  [ 151, "Mew", "psychic", "N/A" ] #,
  # [ 152, "Chikorita", "grass", "N/A" ],
  # [ 153, "Bayleef", "grass", "N/A" ],
  # [ 154, "Meganium", "grass", "N/A" ],
  # [ 155, "Cyndaquil", "fire", "N/A" ],
  # [ 156, "Quilava", "fire", "N/A" ],
  # [ 157, "Typhlosion", "fire", "N/A" ],
  # [ 158, "Totodile", "water", "N/A" ],
  # [ 159, "Croconaw", "water", "N/A" ],
  # [ 160, "Feraligatr", "water", "N/A" ],
  # [ 161, "Sentret", "normal", "N/A" ],
  # [ 162, "Furret", "normal", "N/A" ],
  # [ 163, "Hoothoot", "normal", "flying" ],
  # [ 164, "Noctowl", "normal", "flying" ],
  # [ 165, "Ledyba", "bug", "flying" ],
  # [ 166, "Ledian", "bug", "flying" ],
  # [ 167, "Spinarak", "bug", "poison" ],
  # [ 168, "Ariados", "bug", "poison" ],
  # [ 169, "Crobat", "poison", "flying" ],
  # [ 170, "Chinchou", "water", "electric" ],
  # [ 171, "Lanturn", "water", "electric" ],
  # [ 172, "Pichu", "electric", "N/A" ],
  # [ 173, "Cleffa", "fairy", "N/A" ],
  # [ 174, "Igglybuff", "normal", "fairy" ],
  # [ 175, "Togepi", "fairy", "N/A" ],
  # [ 176, "Togetic", "fairy", "flying" ],
  # [ 177, "Natu", "psychic", "flying" ],
  # [ 178, "Xatu", "psychic", "flying" ],
  # [ 179, "Mareep", "electric", "N/A" ],
  # [ 180, "Flaaffy", "electric", "N/A" ],
  # [ 181, "Ampharos", "electric", "N/A" ],
  # [ 181, "Mega Ampharos", "electric", "dragon" ],
  # [ 182, "Bellossom", "grass", "N/A" ],
  # [ 183, "Marill", "water", "fairy" ],
  # [ 184, "Azumarill", "water", "fairy" ],
  # [ 185, "Sudowoodo", "rock", "N/A" ],
  # [ 186, "Politoed", "water", "N/A" ],
  # [ 187, "Hoppip", "grass", "flying" ],
  # [ 188, "Skiploom", "grass", "flying" ],
  # [ 189, "Jumpluff", "grass", "flying" ],
  # [ 190, "Aipom", "normal", "N/A" ],
  # [ 191, "Sunkern", "grass", "N/A" ],
  # [ 192, "Sunflora", "grass", "N/A" ],
  # [ 193, "Yanma", "bug", "flying" ],
  # [ 194, "Wooper", "water", "ground" ],
  # [ 195, "Quagsire", "water", "ground" ],
  # [ 196, "Espeon", "psychic", "N/A" ],
  # [ 197, "Umbreon", "dark", "N/A" ],
  # [ 198, "Murkrow", "dark", "flying" ],
  # [ 199, "Slowking", "water", "psychic" ],
  # [ 200, "Misdreavus", "ghost", "N/A" ],
  # [ 201, "Unown", "psychic", "N/A" ],
  # [ 202, "Wobbuffet", "psychic", "N/A" ],
  # [ 203, "Girafarig", "normal", "psychic" ],
  # [ 204, "Pineco", "bug", "N/A" ],
  # [ 205, "Forretress", "bug", "steel" ],
  # [ 206, "Dunsparce", "normal", "N/A" ],
  # [ 207, "Gligar", "ground", "flying" ],
  # [ 208, "Steelix", "steel", "ground" ],
  # [ 208, "Mega Steelix", "steel", "ground" ],
  # [ 209, "Snubbull", "fairy", "N/A" ],
  # [ 210, "Granbull", "fairy", "N/A" ],
  # [ 211, "Qwilfish", "water", "poison" ],
  # [ 212, "Scizor", "bug", "steel" ],
  # [ 212, "Mega Scizor", "bug", "steel" ],
  # [ 213, "Shuckle", "bug", "rock" ],
  # [ 214, "Heracross", "bug", "fighting" ],
  # [ 214, "Mega Heracross", "bug", "fighting" ],
  # [ 215, "Sneasel", "dark", "ice" ],
  # [ 216, "Teddiursa", "normal", "N/A" ],
  # [ 217, "Ursaring", "normal", "N/A" ],
  # [ 218, "Slugma", "fire", "N/A" ],
  # [ 219, "Magcargo", "fire", "rock" ],
  # [ 220, "Swinub", "ice", "ground" ],
  # [ 221, "Piloswine", "ice", "ground" ],
  # [ 222, "Corsola", "water", "rock" ],
  # [ 223, "Remoraid", "water", "N/A" ],
  # [ 224, "Octillery", "water", "N/A" ],
  # [ 225, "Delibird", "ice", "flying" ],
  # [ 226, "Mantine", "water", "flying" ],
  # [ 227, "Skarmory", "steel", "flying" ],
  # [ 228, "Houndour", "dark", "fire" ],
  # [ 229, "Houndoom", "dark", "fire" ],
  # [ 229, "Mega Houndoom", "dark", "fire" ],
  # [ 230, "Kingdra", "water", "dragon" ],
  # [ 231, "Phanpy", "ground", "N/A" ],
  # [ 232, "Donphan", "ground", "N/A" ],
  # [ 233, "Porygon2", "normal", "N/A" ],
  # [ 234, "Stantler", "normal", "N/A" ],
  # [ 235, "Smeargle", "normal", "N/A" ],
  # [ 236, "Tyrogue", "fighting", "N/A" ],
  # [ 237, "Hitmontop", "fighting", "N/A" ],
  # [ 238, "Smoochum", "ice", "psychic" ],
  # [ 239, "Elekid", "electric", "N/A" ],
  # [ 240, "Magby", "fire", "N/A" ],
  # [ 241, "Miltank", "normal", "N/A" ],
  # [ 242, "Blissey", "normal", "N/A" ],
  # [ 243, "Raikou", "electric", "N/A" ],
  # [ 244, "Entei", "fire", "N/A" ],
  # [ 245, "Suicune", "water", "N/A" ],
  # [ 246, "Larvitar", "rock", "ground" ],
  # [ 247, "Pupitar", "rock", "ground" ],
  # [ 248, "Tyranitar", "rock", "dark" ],
  # [ 248, "Mega Tyranitar", "rock", "dark" ],
  # [ 249, "Lugia", "psychic", "flying" ],
  # [ 250, "Ho-oh", "fire", "flying" ],
  # [ 251, "Celebi", "psychic", "grass" ],
  # [ 252, "Treecko", "grass", "N/A" ],
  # [ 253, "Grovyle", "grass", "N/A" ],
  # [ 254, "Sceptile", "grass", "N/A" ],
  # [ 254, "Mega Sceptile", "grass", "dragon" ],
  # [ 255, "Torchic", "fire", "N/A" ],
  # [ 256, "Combusken", "fire", "fighting" ],
  # [ 257, "Blaziken", "fire", "fighting" ],
  # [ 257, "Mega Blaziken", "fire", "fighting" ],
  # [ 258, "Mudkip", "water", "N/A" ],
  # [ 259, "Marshtomp", "water", "ground" ],
  # [ 260, "Swampert", "water", "ground" ],
  # [ 260, "Mega Swampert", "water", "ground" ],
  # [ 261, "Poochyena", "dark", "N/A" ],
  # [ 262, "Mightyena", "dark", "N/A" ],
  # [ 263, "Zigzagoon", "normal", "N/A" ],
  # [ 264, "Linoone", "normal", "N/A" ],
  # [ 265, "Wurmple", "bug", "N/A" ],
  # [ 266, "Silcoon", "bug", "N/A" ],
  # [ 267, "Beautifly", "bug", "flying" ],
  # [ 268, "Cascoon", "bug", "N/A" ],
  # [ 269, "Dustox", "bug", "poison" ],
  # [ 270, "Lotad", "water", "grass" ],
  # [ 271, "Lombre", "water", "grass" ],
  # [ 272, "Ludicolo", "water", "grass" ],
  # [ 273, "Seedot", "grass", "N/A" ],
  # [ 274, "Nuzleaf", "grass", "dark" ],
  # [ 275, "Shiftry", "grass", "dark" ],
  # [ 276, "Taillow", "normal", "flying" ],
  # [ 277, "Swellow", "normal", "flying" ],
  # [ 278, "Wingull", "water", "flying" ],
  # [ 279, "Pelipper", "water", "flying" ],
  # [ 280, "Ralts", "psychic", "fairy" ],
  # [ 281, "Kirlia", "psychic", "fairy" ],
  # [ 282, "Gardevoir", "psychic", "fairy" ],
  # [ 282, "Mega Gardevoir", "psychic", "fairy" ],
  # [ 283, "Surskit", "bug", "water" ],
  # [ 284, "Masquerain", "bug", "flying" ],
  # [ 285, "Shroomish", "grass", "N/A" ],
  # [ 286, "Breloom", "grass", "fighting" ],
  # [ 287, "Slakoth", "normal", "N/A" ],
  # [ 288, "Vigoroth", "normal", "N/A" ],
  # [ 289, "Slaking", "normal", "N/A" ],
  # [ 290, "Nincada", "bug", "ground" ],
  # [ 291, "Ninjask", "bug", "flying" ],
  # [ 292, "Shedinja", "bug", "ghost" ],
  # [ 293, "Whismur", "normal", "N/A" ],
  # [ 294, "Loudred", "normal", "N/A" ],
  # [ 295, "Exploud", "normal", "N/A" ],
  # [ 296, "Makuhita", "fighting", "N/A" ],
  # [ 297, "Hariyama", "fighting", "N/A" ],
  # [ 298, "Azurill", "normal", "fairy" ],
  # [ 299, "Nosepass", "rock", "N/A" ],
  # [ 300, "Skitty", "normal", "N/A" ],
  # [ 301, "Delcatty", "normal", "N/A" ],
  # [ 302, "Sableye", "dark", "ghost" ],
  # [ 302, "Mega Sableye", "dark", "ghost" ],
  # [ 303, "Mawile", "steel", "fairy" ],
  # [ 303, "Mega Mawile", "steel", "fairy" ],
  # [ 304, "Aron", "steel", "rock" ],
  # [ 305, "Lairon", "steel", "rock" ],
  # [ 306, "Aggron", "steel", "rock" ],
  # [ 306, "Mega Aggron", "steel", "N/A" ],
  # [ 307, "Meditite", "fighting", "psychic" ],
  # [ 308, "Medicham", "fighting", "psychic" ],
  # [ 308, "Mega Medicham", "fighting", "psychic" ],
  # [ 309, "Electrike", "electric", "N/A" ],
  # [ 310, "Manectric", "electric", "N/A" ],
  # [ 310, "Mega Manectric", "electric", "N/A" ],
  # [ 311, "Plusle", "electric", "N/A" ],
  # [ 312, "Minun", "electric", "N/A" ],
  # [ 313, "Volbeat", "bug", "N/A" ],
  # [ 314, "Illumise", "bug", "N/A" ],
  # [ 315, "Roselia", "grass", "poison" ],
  # [ 316, "Gulpin", "poison", "N/A" ],
  # [ 317, "Swalot", "poison", "N/A" ],
  # [ 318, "Carvanha", "water", "dark" ],
  # [ 319, "Sharpedo", "water", "dark" ],
  # [ 319, "Mega Sharpedo", "water", "dark" ],
  # [ 320, "Wailmer", "water", "N/A" ],
  # [ 321, "Wailord", "water", "N/A" ],
  # [ 322, "Numel", "fire", "ground" ],
  # [ 323, "Camerupt", "fire", "ground" ],
  # [ 323, "Mega Camerupt", "fire", "ground" ],
  # [ 324, "Torkoal", "fire", "N/A" ],
  # [ 325, "Spoink", "psychic", "N/A" ],
  # [ 326, "Grumpig", "psychic", "N/A" ],
  # [ 327, "Spinda", "normal", "N/A" ],
  # [ 328, "Trapinch", "ground", "N/A" ],
  # [ 329, "Vibrava", "ground", "dragon" ],
  # [ 330, "Flygon", "ground", "dragon" ],
  # [ 331, "Cacnea", "grass", "N/A" ],
  # [ 332, "Cacturne", "grass", "dark" ],
  # [ 333, "Swablu", "normal", "flying" ],
  # [ 334, "Altaria", "dragon", "flying" ],
  # [ 334, "Mega Altaria", "dragon", "fairy" ],
  # [ 335, "Zangoose", "normal", "N/A" ],
  # [ 336, "Seviper", "poison", "N/A" ],
  # [ 337, "Lunatone", "rock", "psychic" ],
  # [ 338, "Solrock", "rock", "psychic" ],
  # [ 339, "Barboach", "water", "ground" ],
  # [ 340, "Whiscash", "water", "ground" ],
  # [ 341, "Corphish", "water", "N/A" ],
  # [ 342, "Crawdaunt", "water", "dark" ],
  # [ 343, "Baltoy", "ground", "psychic" ],
  # [ 344, "Claydol", "ground", "psychic" ],
  # [ 345, "Lileep", "rock", "grass" ],
  # [ 346, "Cradily", "rock", "grass" ],
  # [ 347, "Anorith", "rock", "bug" ],
  # [ 348, "Armaldo", "rock", "bug" ],
  # [ 349, "Feebas", "water", "N/A" ],
  # [ 350, "Milotic", "water", "N/A" ],
  # [ 351, "Castform", "normal", "N/A" ],
  # [ 351, "Sunny Form", "fire", "N/A" ],
  # [ 351, "Rainy Form", "water", "N/A" ],
  # [ 351, "Snowy Form", "ice", "N/A" ],
  # [ 352, "Kecleon", "normal", "N/A" ],
  # [ 353, "Shuppet", "ghost", "N/A" ],
  # [ 354, "Banette", "ghost", "N/A" ],
  # [ 354, "Mega Banette", "ghost", "N/A" ],
  # [ 355, "Duskull", "ghost", "N/A" ],
  # [ 356, "Dusclops", "ghost", "N/A" ],
  # [ 357, "Tropius", "grass", "flying" ],
  # [ 358, "Chimecho", "psychic", "N/A" ],
  # [ 359, "Absol", "dark", "N/A" ],
  # [ 359, "Mega Absol", "dark", "N/A" ],
  # [ 360, "Wynaut", "psychic", "N/A" ],
  # [ 361, "Snorunt", "ice", "N/A" ],
  # [ 362, "Glalie", "ice", "N/A" ],
  # [ 362, "Mega Glalie", "ice", "N/A" ],
  # [ 363, "Spheal", "ice", "water" ],
  # [ 364, "Sealeo", "ice", "water" ],
  # [ 365, "Walrein", "ice", "water" ],
  # [ 366, "Clamperl", "water", "N/A" ],
  # [ 367, "Huntail", "water", "N/A" ],
  # [ 368, "Gorebyss", "water", "N/A" ],
  # [ 369, "Relicanth", "water", "rock" ],
  # [ 370, "Luvdisc", "water", "N/A" ],
  # [ 371, "Bagon", "dragon", "N/A" ],
  # [ 372, "Shelgon", "dragon", "N/A" ],
  # [ 373, "Salamence", "dragon", "flying" ],
  # [ 373, "Mega Salamence", "dragon", "flying" ],
  # [ 374, "Beldum", "steel", "psychic" ],
  # [ 375, "Metang", "steel", "psychic" ],
  # [ 376, "Metagross", "steel", "psychic" ],
  # [ 376, "Mega Metagross", "steel", "psychic" ],
  # [ 377, "Regirock", "rock", "N/A" ],
  # [ 378, "Regice", "ice", "N/A" ],
  # [ 379, "Registeel", "steel", "N/A" ],
  # [ 380, "Latias", "dragon", "psychic" ],
  # [ 380, "Mega Latias", "dragon", "psychic" ],
  # [ 381, "Latios", "dragon", "psychic" ],
  # [ 381, "Mega Latios", "dragon", "psychic" ],
  # [ 382, "Kyogre", "water", "N/A" ],
  # [ 382, "Primal Kyogre", "water", "N/A" ],
  # [ 383, "Groudon", "ground", "N/A" ],
  # [ 383, "Primal Groudon", "ground", "fire" ],
  # [ 384, "Rayquaza", "dragon", "flying" ],
  # [ 384, "Mega Rayquaza", "dragon", "flying" ],
  # [ 385, "Jirachi", "steel", "psychic" ],
  # [ 386, "Deoxys Normal Form", "psychic", "N/A" ],
  # [ 386, "Deoxys Attack Form", "psychic", "N/A" ],
  # [ 386, "Deoxys Defense Form", "psychic", "N/A" ],
  # [ 386, "Deoxys Speed Form", "psychic", "N/A" ],
  # [ 387, "Turtwig", "grass", "N/A" ],
  # [ 388, "Grotle", "grass", "N/A" ],
  # [ 389, "Torterra", "grass", "ground" ],
  # [ 390, "Chimchar", "fire", "N/A" ],
  # [ 391, "Monferno", "fire", "fighting" ],
  # [ 392, "Infernape", "fire", "fighting" ],
  # [ 393, "Piplup", "water", "N/A" ],
  # [ 394, "Prinplup", "water", "N/A" ],
  # [ 395, "Empoleon", "water", "steel" ],
  # [ 396, "Starly", "normal", "flying" ],
  # [ 397, "Staravia", "normal", "flying" ],
  # [ 398, "Staraptor", "normal", "flying" ],
  # [ 399, "Bidoof", "normal", "N/A" ],
  # [ 400, "Bibarel", "normal", "water" ],
  # [ 401, "Kricketot", "bug", "N/A" ],
  # [ 402, "Kricketune", "bug", "N/A" ],
  # [ 403, "Shinx", "electric", "N/A" ],
  # [ 404, "Luxio", "electric", "N/A" ],
  # [ 405, "Luxray", "electric", "N/A" ],
  # [ 406, "Budew", "grass", "poison" ],
  # [ 407, "Roserade", "grass", "poison" ],
  # [ 408, "Cranidos", "rock", "N/A" ],
  # [ 409, "Rampardos", "rock", "N/A" ],
  # [ 410, "Shieldon", "rock", "steel" ],
  # [ 411, "Bastiodon", "rock", "steel" ],
  # [ 412, "Burmy", "bug", "N/A" ],
  # [ 413, "Wormadam Plant Cloak", "bug", "grass" ],
  # [ 413, "Wormadam Sandy Cloak", "bug", "ground" ],
  # [ 413, "Wormadam Trash Cloak", "bug", "steel" ],
  # [ 414, "Mothim", "bug", "flying" ],
  # [ 415, "Combee", "bug", "flying" ],
  # [ 416, "Vespiquen", "bug", "flying" ],
  # [ 417, "Pachirisu", "electric", "N/A" ],
  # [ 418, "Buizel", "water", "N/A" ],
  # [ 419, "Floatzel", "water", "N/A" ],
  # [ 420, "Cherubi", "grass", "N/A" ],
  # [ 421, "Cherrim", "grass", "N/A" ],
  # [ 422, "Shellos", "water", "N/A" ],
  # [ 423, "Gastrodon", "water", "ground" ],
  # [ 424, "Ambipom", "normal", "N/A" ],
  # [ 425, "Drifloon", "ghost", "flying" ],
  # [ 426, "Drifblim", "ghost", "flying" ],
  # [ 427, "Buneary", "normal", "N/A" ],
  # [ 428, "Lopunny", "normal", "N/A" ],
  # [ 428, "Mega Lopunny", "normal", "fighting" ],
  # [ 429, "Mismagius", "ghost", "N/A" ],
  # [ 430, "Honchkrow", "dark", "flying" ],
  # [ 431, "Glameow", "normal", "N/A" ],
  # [ 432, "Purugly", "normal", "N/A" ],
  # [ 433, "Chingling", "psychic", "N/A" ],
  # [ 434, "Stunky", "poison", "dark" ],
  # [ 435, "Skuntank", "poison", "dark" ],
  # [ 436, "Bronzor", "steel", "psychic" ],
  # [ 437, "Bronzong", "steel", "psychic" ],
  # [ 438, "Bonsly", "rock", "N/A" ],
  # [ 439, "Mime Jr.", "psychic", "fairy" ],
  # [ 440, "Happiny", "normal", "N/A" ],
  # [ 441, "Chatot", "normal", "flying" ],
  # [ 442, "Spiritomb", "ghost", "dark" ],
  # [ 443, "Gible", "dragon", "ground" ],
  # [ 444, "Gabite", "dragon", "ground" ],
  # [ 445, "Garchomp", "dragon", "ground" ],
  # [ 445, "Mega Garchomp", "dragon", "ground" ],
  # [ 446, "Munchlax", "normal", "N/A" ],
  # [ 447, "Riolu", "fighting", "N/A" ],
  # [ 448, "Lucario", "fighting", "steel" ],
  # [ 448, "Mega Lucario", "fighting", "steel" ],
  # [ 449, "Hippopotas", "ground", "N/A" ],
  # [ 450, "Hippowdon", "ground", "N/A" ],
  # [ 451, "Skorupi", "poison", "bug" ],
  # [ 452, "Drapion", "poison", "dark" ],
  # [ 453, "Croagunk", "poison", "fighting" ],
  # [ 454, "Toxicroak", "poison", "fighting" ],
  # [ 455, "Carnivine", "grass", "N/A" ],
  # [ 456, "Finneon", "water", "N/A" ],
  # [ 457, "Lumineon", "water", "N/A" ],
  # [ 458, "Mantyke", "water", "flying" ],
  # [ 459, "Snover", "grass", "ice" ],
  # [ 460, "Abomasnow", "grass", "ice" ],
  # [ 460, "Mega Abomasnow", "grass", "ice" ],
  # [ 461, "Weavile", "dark", "ice" ],
  # [ 462, "Magnezone", "electric", "steel" ],
  # [ 463, "Lickilicky", "normal", "N/A" ],
  # [ 464, "Rhyperior", "ground", "rock" ],
  # [ 465, "Tangrowth", "grass", "N/A" ],
  # [ 466, "Electivire", "electric", "N/A" ],
  # [ 467, "Magmortar", "fire", "N/A" ],
  # [ 468, "Togekiss", "fairy", "flying" ],
  # [ 469, "Yanmega", "bug", "flying" ],
  # [ 470, "Leafeon", "grass", "N/A" ],
  # [ 471, "Glaceon", "ice", "N/A" ],
  # [ 472, "Gliscor", "ground", "flying" ],
  # [ 473, "Mamoswine", "ice", "ground" ],
  # [ 474, "Porygon-Z", "normal", "N/A" ],
  # [ 475, "Gallade", "psychic", "fighting" ],
  # [ 475, "Mega Gallade", "psychic", "fighting" ],
  # [ 476, "Probopass", "rock", "steel" ],
  # [ 477, "Dusknoir", "ghost", "N/A" ],
  # [ 478, "Froslass", "ice", "ghost" ],
  # [ 479, "Rotom", "electric", "ghost" ],
  # [ 479, "Heat Rotom", "electric", "fire" ],
  # [ 479, "Wash Rotom", "electric", "water" ],
  # [ 479, "Frost Rotom", "electric", "ice" ],
  # [ 479, "Fan Rotom", "electric", "flying" ],
  # [ 479, "Mow Rotom", "electric", "grass" ],
  # [ 480, "Uxie", "psychic", "N/A" ],
  # [ 481, "Mesprit", "psychic", "N/A" ],
  # [ 482, "Azelf", "psychic", "N/A" ],
  # [ 483, "Dialga", "steel", "dragon" ],
  # [ 484, "Palkia", "water", "dragon" ],
  # [ 485, "Heatran", "fire", "steel" ],
  # [ 486, "Regigigas", "normal", "N/A" ],
  # [ 487, "Giratina Altered Form", "ghost", "dragon" ],
  # [ 487, "Giratina Origin Form", "ghost", "dragon" ],
  # [ 488, "Cresselia", "psychic", "N/A" ],
  # [ 489, "Phione", "water", "N/A" ],
  # [ 490, "Manaphy", "water", "N/A" ],
  # [ 491, "Darkrai", "dark", "N/A" ],
  # [ 492, "Shaymin Land Form", "grass", "N/A" ],
  # [ 492, "Shaymin Sky Form", "grass", "flying" ],
  # [ 493, "Arceus", "normal", "N/A" ],
  # [ 494, "Victini", "psychic", "fire" ],
  # [ 495, "Snivy", "grass", "N/A" ],
  # [ 496, "Servine", "grass", "N/A" ],
  # [ 497, "Serperior", "grass", "N/A" ],
  # [ 498, "Tepig", "fire", "N/A" ],
  # [ 499, "Pignite", "fire", "fighting" ],
  # [ 500, "Emboar", "fire", "fighting" ],
  # [ 501, "Oshawott", "water", "N/A" ],
  # [ 502, "Dewott", "water", "N/A" ],
  # [ 503, "Samurott", "water", "N/A" ],
  # [ 504, "Patrat", "normal", "N/A" ],
  # [ 505, "Watchog", "normal", "N/A" ],
  # [ 506, "Lillipup", "normal", "N/A" ],
  # [ 507, "Herdier", "normal", "N/A" ],
  # [ 508, "Stoutland", "normal", "N/A" ],
  # [ 509, "Purrloin", "dark", "N/A" ],
  # [ 510, "Liepard", "dark", "N/A" ],
  # [ 511, "Pansage", "grass", "N/A" ],
  # [ 512, "Simisage", "grass", "N/A" ],
  # [ 513, "Pansear", "fire", "N/A" ],
  # [ 514, "Simisear", "fire", "N/A" ],
  # [ 515, "Panpour", "water", "N/A" ],
  # [ 516, "Simipour", "water", "N/A" ],
  # [ 517, "Munna", "psychic", "N/A" ],
  # [ 518, "Musharna", "psychic", "N/A" ],
  # [ 519, "Pidove", "normal", "flying" ],
  # [ 520, "Tranquill", "normal", "flying" ],
  # [ 521, "Unfezant", "normal", "flying" ],
  # [ 522, "Blitzle", "electric", "N/A" ],
  # [ 523, "Zebstrika", "electric", "N/A" ],
  # [ 524, "Roggenrola", "rock", "N/A" ],
  # [ 525, "Boldore", "rock", "N/A" ],
  # [ 526, "Gigalith", "rock", "N/A" ],
  # [ 527, "Woobat", "psychic", "flying" ],
  # [ 528, "Swoobat", "psychic", "flying" ],
  # [ 529, "Drilbur", "ground", "N/A" ],
  # [ 530, "Excadrill", "ground", "steel" ],
  # [ 531, "Audino", "normal", "N/A" ],
  # [ 531, "Mega Audino", "normal", "fairy" ],
  # [ 532, "Timburr", "fighting", "N/A" ],
  # [ 533, "Gurdurr", "fighting", "N/A" ],
  # [ 534, "Conkeldurr", "fighting", "N/A" ],
  # [ 535, "Tympole", "water", "N/A" ],
  # [ 536, "Palpitoad", "water", "ground" ],
  # [ 537, "Seismitoad", "water", "ground" ],
  # [ 538, "Throh", "fighting", "N/A" ],
  # [ 539, "Sawk", "fighting", "N/A" ],
  # [ 540, "Sewaddle", "bug", "grass" ],
  # [ 541, "Swadloon", "bug", "grass" ],
  # [ 542, "Leavanny", "bug", "grass" ],
  # [ 543, "Venipede", "bug", "poison" ],
  # [ 544, "Whirlipede", "bug", "poison" ],
  # [ 545, "Scolipede", "bug", "poison" ],
  # [ 546, "Cottonee", "grass", "fairy" ],
  # [ 547, "Whimsicott", "grass", "fairy" ],
  # [ 548, "Petilil", "grass", "N/A" ],
  # [ 549, "Lilligant", "grass", "N/A" ],
  # [ 550, "Basculin Red-Striped Form", "water", "N/A" ],
  # [ 550, "Basculin Blue-Striped Form", "water", "N/A" ],
  # [ 551, "Sandile", "ground", "dark" ],
  # [ 552, "Krokorok", "ground", "dark" ],
  # [ 553, "Krookodile", "ground", "dark" ],
  # [ 554, "Darumaka", "fire", "N/A" ],
  # [ 555, "Darmanitan Standard Mode", "fire", "N/A" ],
  # [ 555, "Darmanitan Zen Mode", "fire", "psychic" ],
  # [ 556, "Maractus", "grass", "N/A" ],
  # [ 557, "Dwebble", "bug", "rock" ],
  # [ 558, "Crustle", "bug", "rock" ],
  # [ 559, "Scraggy", "dark", "fighting" ],
  # [ 560, "Scrafty", "dark", "fighting" ],
  # [ 561, "Sigilyph", "psychic", "flying" ],
  # [ 562, "Yamask", "ghost", "N/A" ],
  # [ 563, "Cofagrigus", "ghost", "N/A" ],
  # [ 564, "Tirtouga", "water", "rock" ],
  # [ 565, "Carracosta", "water", "rock" ],
  # [ 566, "Archen", "rock", "flying" ],
  # [ 567, "Archeops", "rock", "flying" ],
  # [ 568, "Trubbish", "poison", "N/A" ],
  # [ 569, "Garbodor", "poison", "N/A" ],
  # [ 570, "Zorua", "dark", "N/A" ],
  # [ 571, "Zoroark", "dark", "N/A" ],
  # [ 572, "Minccino", "normal", "N/A" ],
  # [ 573, "Cinccino", "normal", "N/A" ],
  # [ 574, "Gothita", "psychic", "N/A" ],
  # [ 575, "Gothorita", "psychic", "N/A" ],
  # [ 576, "Gothitelle", "psychic", "N/A" ],
  # [ 577, "Solosis", "psychic", "N/A" ],
  # [ 578, "Duosion", "psychic", "N/A" ],
  # [ 579, "Reuniclus", "psychic", "N/A" ],
  # [ 580, "Ducklett", "water", "flying" ],
  # [ 581, "Swanna", "water", "flying" ],
  # [ 582, "Vanillite", "ice", "N/A" ],
  # [ 583, "Vanillish", "ice", "N/A" ],
  # [ 584, "Vanilluxe", "ice", "N/A" ],
  # [ 585, "Deerling", "normal", "grass" ],
  # [ 586, "Sawsbuck", "normal", "grass" ],
  # [ 587, "Emolga", "electric", "flying" ],
  # [ 588, "Karrablast", "bug", "N/A" ],
  # [ 589, "Escavalier", "bug", "steel" ],
  # [ 590, "Foongus", "grass", "poison" ],
  # [ 591, "Amoonguss", "grass", "poison" ],
  # [ 592, "Frillish", "water", "ghost" ],
  # [ 593, "Jellicent", "water", "ghost" ],
  # [ 594, "Alomomola", "water", "N/A" ],
  # [ 595, "Joltik", "bug", "electric" ],
  # [ 596, "Galvantula", "bug", "electric" ],
  # [ 597, "Ferroseed", "grass", "steel" ],
  # [ 598, "Ferrothorn", "grass", "steel" ],
  # [ 599, "Klink", "steel", "N/A" ],
  # [ 600, "Klang", "steel", "N/A" ],
  # [ 601, "Klinklang", "steel", "N/A" ],
  # [ 602, "Tynamo", "electric", "N/A" ],
  # [ 603, "Eelektrik", "electric", "N/A" ],
  # [ 604, "Eelektross", "electric", "N/A" ],
  # [ 605, "Elgyem", "psychic", "N/A" ],
  # [ 606, "Beheeyem", "psychic", "N/A" ],
  # [ 607, "Litwick", "ghost", "fire" ],
  # [ 608, "Lampent", "ghost", "fire" ],
  # [ 609, "Chandelure", "ghost", "fire" ],
  # [ 610, "Axew", "dragon", "N/A" ],
  # [ 611, "Fraxure", "dragon", "N/A" ],
  # [ 612, "Haxorus", "dragon", "N/A" ],
  # [ 613, "Cubchoo", "ice", "N/A" ],
  # [ 614, "Beartic", "ice", "N/A" ],
  # [ 615, "Cryogonal", "ice", "N/A" ],
  # [ 616, "Shelmet", "bug", "N/A" ],
  # [ 617, "Accelgor", "bug", "N/A" ],
  # [ 618, "Stunfisk", "ground", "electric" ],
  # [ 619, "Mienfoo", "fighting", "N/A" ],
  # [ 620, "Mienshao", "fighting", "N/A" ],
  # [ 621, "Druddigon", "dragon", "N/A" ],
  # [ 622, "Golett", "ground", "ghost" ],
  # [ 623, "Golurk", "ground", "ghost" ],
  # [ 624, "Pawniard", "dark", "steel" ],
  # [ 625, "Bisharp", "dark", "steel" ],
  # [ 626, "Bouffalant", "normal", "N/A" ],
  # [ 627, "Rufflet", "normal", "flying" ],
  # [ 628, "Braviary", "normal", "flying" ],
  # [ 629, "Vullaby", "dark", "flying" ],
  # [ 630, "Mandibuzz", "dark", "flying" ],
  # [ 631, "Heatmor", "fire", "N/A" ],
  # [ 632, "Durant", "bug", "steel" ],
  # [ 633, "Deino", "dark", "dragon" ],
  # [ 634, "Zweilous", "dark", "dragon" ],
  # [ 635, "Hydreigon", "dark", "dragon" ],
  # [ 636, "Larvesta", "bug", "fire" ],
  # [ 637, "Volcarona", "bug", "fire" ],
  # [ 638, "Cobalion", "steel", "fighting" ],
  # [ 639, "Terrakion", "rock", "fighting" ],
  # [ 640, "Virizion", "grass", "fighting" ],
  # [ 641, "Tornadus Incarnate Form", "flying", "N/A" ],
  # [ 641, "Tornadus Therian Form", "flying", "N/A" ],
  # [ 642, "Thundurus Incarnate Form", "electric", "flying" ],
  # [ 642, "Thundurus Therian Form", "electric", "flying" ],
  # [ 643, "Reshiram", "dragon", "fire" ],
  # [ 644, "Zekrom", "dragon", "electric" ],
  # [ 645, "Landorus Incarnate Form", "ground", "flying" ],
  # [ 645, "Landorus Therian Form", "ground", "flying" ],
  # [ 646, "Kyurem", "dragon", "ice" ],
  # [ 646, "Kyurem Black Kyurem", "dragon", "ice" ],
  # [ 646, "Kyurem White Kyurem", "dragon", "ice" ],
  # [ 647, "Keldeo Ordinary Form", "water", "fighting" ],
  # [ 647, "Keldeo Resolute Form", "water", "fighting" ],
  # [ 648, "Meloetta Aria Form", "normal", "psychic" ],
  # [ 648, "Meloetta Pirouette Form", "normal", "fighting" ],
  # [ 649, "Genesect", "bug", "steel" ],
  # [ 650, "Chespin", "grass", "N/A" ],
  # [ 651, "Quilladin", "grass", "N/A" ],
  # [ 652, "Chesnaught", "grass", "fighting" ],
  # [ 653, "Fennekin", "fire", "N/A" ],
  # [ 654, "Braixen", "fire", "N/A" ],
  # [ 655, "Delphox", "fire", "psychic" ],
  # [ 656, "Froakie", "water", "N/A" ],
  # [ 657, "Frogadier", "water", "N/A" ],
  # [ 658, "Greninja", "water", "dark" ],
  # [ 658, "Ash-Greninja", "water", "dark" ],
  # [ 659, "Bunnelby", "normal", "N/A" ],
  # [ 660, "Diggersby", "normal", "ground" ],
  # [ 661, "Fletchling", "normal", "flying" ],
  # [ 662, "Fletchinder", "fire", "flying" ],
  # [ 663, "Talonflame", "fire", "flying" ],
  # [ 664, "Scatterbug", "bug", "N/A" ],
  # [ 665, "Spewpa", "bug", "N/A" ],
  # [ 666, "Vivillon", "bug", "flying" ],
  # [ 667, "Litleo", "fire", "normal" ],
  # [ 668, "Pyroar", "fire", "normal" ],
  # [ 669, "Flabébé", "fairy", "N/A" ],
  # [ 670, "Floette", "fairy", "N/A" ],
  # [ 671, "Florges", "fairy", "N/A" ],
  # [ 672, "Skiddo", "grass", "N/A" ],
  # [ 673, "Gogoat", "grass", "N/A" ],
  # [ 674, "Pancham", "fighting", "N/A" ],
  # [ 675, "Pangoro", "fighting", "dark" ],
  # [ 676, "Furfrou", "normal", "N/A" ],
  # [ 677, "Espurr", "psychic", "N/A" ],
  # [ 678, "Meowstic Male", "psychic", "N/A" ],
  # [ 678, "Meowstic Female", "psychic", "N/A" ],
  # [ 679, "Honedge", "steel", "ghost" ],
  # [ 680, "Doublade", "steel", "ghost" ],
  # [ 681, "Aegislash Blade Form", "steel", "ghost" ],
  # [ 681, "Aegislash Shield Form", "steel", "ghost" ],
  # [ 682, "Spritzee", "fairy", "N/A" ],
  # [ 683, "Aromatisse", "fairy", "N/A" ],
  # [ 684, "Swirlix", "fairy", "N/A" ],
  # [ 685, "Slurpuff", "fairy", "N/A" ],
  # [ 686, "Inkay", "dark", "psychic" ],
  # [ 687, "Malamar", "dark", "psychic" ],
  # [ 688, "Binacle", "rock", "water" ],
  # [ 689, "Barbaracle", "rock", "water" ],
  # [ 690, "Skrelp", "poison", "water" ],
  # [ 691, "Dragalge", "poison", "dragon" ],
  # [ 692, "Clauncher", "water", "N/A" ],
  # [ 693, "Clawitzer", "water", "N/A" ],
  # [ 694, "Helioptile", "electric", "normal" ],
  # [ 695, "Heliolisk", "electric", "normal" ],
  # [ 696, "Tyrunt", "rock", "dragon" ],
  # [ 697, "Tyrantrum", "rock", "dragon" ],
  # [ 698, "Amaura", "rock", "ice" ],
  # [ 699, "Aurorus", "rock", "ice" ],
  # [ 700, "Sylveon", "fairy", "N/A" ],
  # [ 701, "Hawlucha", "fighting", "flying" ],
  # [ 702, "Dedenne", "electric", "fairy" ],
  # [ 703, "Carbink", "rock", "fairy" ],
  # [ 704, "Goomy", "dragon", "N/A" ],
  # [ 705, "Sliggoo", "dragon", "N/A" ],
  # [ 706, "Goodra", "dragon", "N/A" ],
  # [ 707, "Klefki", "steel", "fairy" ],
  # [ 708, "Phantump", "ghost", "grass" ],
  # [ 709, "Trevenant", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Average Size", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Small Size", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Large Size", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Super Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Average Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Small Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Large Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Super Size", "ghost", "grass" ],
  # [ 712, "Bergmite", "ice", "N/A" ],
  # [ 713, "Avalugg", "ice", "N/A" ],
  # [ 714, "Noibat", "flying", "dragon" ],
  # [ 715, "Noivern", "flying", "dragon" ],
  # [ 716, "Xerneas", "fairy", "N/A" ],
  # [ 717, "Yveltal", "dark", "flying" ],
  # [ 718, "Zygarde 50\% Form", "dragon", "ground" ],
  # [ 718, "Zygarde 10\% Form", "dragon", "ground" ],
  # [ 718, "Zygarde Complete Form", "dragon", "ground" ],
  # [ 719, "Diancie", "rock", "fairy" ],
  # [ 719, "Mega Diancie", "rock", "fairy" ],
  # [ 720, "Hoopa Confined", "psychic", "ghost" ],
  # [ 720, "Hoopa Unbound", "psychic", "dark" ],
  # [ 721, "Volcanion", "fire", "water" ],
  # [ 722, "Rowlet", "grass", "flying" ],
  # [ 723, "Dartrix", "grass", "flying" ],
  # [ 724, "Decidueye", "grass", "ghost" ],
  # [ 725, "Litten", "fire", "N/A" ],
  # [ 726, "Torracat", "fire", "N/A" ],
  # [ 727, "Incineroar", "fire", "dark" ],
  # [ 728, "Popplio", "water", "N/A" ],
  # [ 729, "Brionne", "water", "N/A" ],
  # [ 730, "Primarina", "water", "fairy" ],
  # [ 731, "Pikipek", "normal", "flying" ],
  # [ 732, "Trumbeak", "normal", "flying" ],
  # [ 733, "Toucannon", "normal", "flying" ],
  # [ 734, "Yungoos", "normal", "N/A" ],
  # [ 735, "Gumshoos", "normal", "N/A" ],
  # [ 736, "Grubbin", "bug", "N/A" ],
  # [ 737, "Charjabug", "bug", "electric" ],
  # [ 738, "Vikavolt", "bug", "electric" ],
  # [ 739, "Crabrawler", "fighting", "N/A" ],
  # [ 740, "Crabominable", "fighting", "ice" ],
  # [ 741, "Oricorio Baile Style", "fire", "flying" ],
  # [ 741, "Oricorio Pom-Pom Style", "electric", "flying" ],
  # [ 741, "Oricorio Pa'u Style", "psychic", "flying" ],
  # [ 741, "Oricorio Sensu Style", "ghost", "flying" ],
  # [ 742, "Cutiefly", "bug", "fairy" ],
  # [ 743, "Ribombee", "bug", "fairy" ],
  # [ 744, "Rockruff", "rock", "N/A" ],
  # [ 744, "Own Tempo Rockruff", "rock", "N/A" ],
  # [ 745, "Lycanroc Midday Form", "rock", "N/A" ],
  # [ 745, "Lycanroc Midnight Form", "rock", "N/A" ],
  # [ 745, "Lycanroc Dusk Form", "rock", "N/A" ],
  # [ 746, "Wishiwashi Solo Form", "water", "N/A" ],
  # [ 746, "Wishiwashi School Form", "water", "N/A" ],
  # [ 747, "Mareanie", "poison", "water" ],
  # [ 748, "Toxapex", "poison", "water" ],
  # [ 749, "Mudbray", "ground", "N/A" ],
  # [ 750, "Mudsdale", "ground", "N/A" ],
  # [ 751, "Dewpider", "water", "bug" ],
  # [ 752, "Araquanid", "water", "bug" ],
  # [ 753, "Fomantis", "grass", "N/A" ],
  # [ 754, "Lurantis", "grass", "N/A" ],
  # [ 755, "Morelull", "grass", "fairy" ],
  # [ 756, "Shiinotic", "grass", "fairy" ],
  # [ 757, "Salandit", "poison", "fire" ],
  # [ 758, "Salazzle", "poison", "fire" ],
  # [ 759, "Stufful", "normal", "fighting" ],
  # [ 760, "Bewear", "normal", "fighting" ],
  # [ 761, "Bounsweet", "grass", "N/A" ],
  # [ 762, "Steenee", "grass", "N/A" ],
  # [ 763, "Tsareena", "grass", "N/A" ],
  # [ 764, "Comfey", "fairy", "N/A" ],
  # [ 765, "Oranguru", "normal", "psychic" ],
  # [ 766, "Passimian", "fighting", "N/A" ],
  # [ 767, "Wimpod", "bug", "water" ],
  # [ 768, "Golisopod", "bug", "water" ],
  # [ 769, "Sandygast", "ghost", "ground" ],
  # [ 770, "Palossand", "ghost", "ground" ],
  # [ 771, "Pyukumuku", "water", "N/A" ],
  # [ 772, "Type: Null", "normal", "N/A" ],
  # [ 773, "Silvally", "normal", "N/A" ],
  # [ 774, "Minior Meteor Form", "rock", "flying" ],
  # [ 774, "Minior Core Form", "rock", "flying" ],
  # [ 775, "Komala", "normal", "N/A" ],
  # [ 776, "Turtonator", "fire", "dragon" ],
  # [ 777, "Togedemaru", "electric", "steel" ],
  # [ 778, "Mimikyu", "ghost", "fairy" ],
  # [ 779, "Bruxish", "water", "psychic" ],
  # [ 780, "Drampa", "normal", "dragon" ],
  # [ 781, "Dhelmise", "ghost", "grass" ],
  # [ 782, "Jangmo-o", "dragon", "N/A" ],
  # [ 783, "Hakamo-o", "dragon", "fighting" ],
  # [ 784, "Kommo-o", "dragon", "fighting" ],
  # [ 785, "Tapu Koko", "electric", "fairy" ],
  # [ 786, "Tapu Lele", "psychic", "fairy" ],
  # [ 787, "Tapu Bulu", "grass", "fairy" ],
  # [ 788, "Tapu Fini", "water", "fairy" ],
  # [ 789, "Cosmog", "psychic", "N/A" ],
  # [ 790, "Cosmoem", "psychic", "N/A" ],
  # [ 791, "Solgaleo", "psychic", "steel" ],
  # [ 792, "Lunala", "psychic", "ghost" ],
  # [ 793, "Nihilego", "rock", "poison" ],
  # [ 794, "Buzzwole", "bug", "fighting" ],
  # [ 795, "Pheromosa", "bug", "fighting" ],
  # [ 796, "Xurkitree", "electric", "N/A" ],
  # [ 797, "Celesteela", "steel", "flying" ],
  # [ 798, "Kartana", "grass", "steel" ],
  # [ 799, "Guzzlord", "dark", "dragon" ],
  # [ 800, "Necrozma", "psychic", "N/A" ],
  # [ 800, "Dusk Mane Necrozma", "psychic", "steel" ],
  # [ 800, "Dawn Wings Necrozma", "psychic", "ghost" ],
  # [ 800, "Ultra Necrozma", "psychic", "dragon" ],
  # [ 801, "Magearna", "steel", "fairy" ],
  # [ 802, "Marshadow", "fighting", "ghost" ],
  # [ 803, "Poipole", "poison", "N/A" ],
  # [ 804, "Naganadel", "poison", "dragon" ],
  # [ 805, "Stakataka", "rock", "steel" ],
  # [ 806, "Blacephalon", "fire", "ghost" ],
  # [ 807, "Zeraora", "electric", "N/A" ],
  # [ 808, "Meltan", "steel", "N/A" ],
  # [ 809, "Melmetal", "steel", "N/A" ]
]

pokemon_list.each do |pdNum, pmName, type1, type2|
  Pokemon.create( pokedex_number: pdNum, name: pmName, type1: type1, type2: type2)
end