# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

pokemon_list = [
  [ 1, "Bulbasaur", "grass", "poison" ],
  [ 2, "Ivysaur", "grass", "poison" ],
  [ 3, "Venusaur", "grass", "poison" ],

  # # [ 3, "Mega Venusaur", "grass", "poison" ],

  [ 4, "Charmander", "fire", "N/A" ],
  [ 5, "Charmeleon", "fire", "N/A" ],
  [ 6, "Charizard", "fire", "flying" ],

  # # [ 6, "Mega Charizard X", "fire", "dragon" ],
  # # [ 6, "Mega Charizard Y", "fire", "flying" ],

  [ 7, "Squirtle", "water", "N/A" ],
  [ 8, "Wartortle", "water", "N/A" ],
  [ 9, "Blastoise", "water", "N/A" ],

  # # [ 9, "Mega Blastoise", "water", "N/A" ],

  [ 10, "Caterpie", "bug", "N/A" ],
  # [ 11, "Metapod", "bug", "N/A" ],
  # [ 12, "Butterfree", "bug", "flying" ],
  # [ 13, "Weedle", "bug", "poison" ],
  # [ 14, "Kakuna", "bug", "poison" ],
  # [ 15, "Beedrill", "bug", "poison" ],

  # # [ 15, "Mega Beedrill", "bug", "poison" ],

  # [ 16, "Pidgey", "normal", "flying" ],
  # [ 17, "Pidgeotto", "normal", "flying" ],
  # [ 18, "Pidgeot", "normal", "flying" ],

  # # [ 18, "Mega Pidgeot", "normal", "flying" ],

  # [ 19, "Rattata", "normal", "N/A" ],

  # # [ 19, "Alolan Rattata", "dark", "normal" ],

  # [ 20, "Raticate", "normal", "N/A" ],

  # # [ 20, "Alolan Raticate", "dark", "normal" ],

  # [ 21, "Spearow", "normal", "flying" ],
  # [ 22, "Fearow", "normal", "flying" ],
  # [ 23, "Ekans", "poison", "N/A" ],
  # [ 24, "Arbok", "poison", "N/A" ],
  # [ 25, "Pikachu", "electric", "N/A" ],

  # # [ 25, "Partner Pikachu", "electric", "N/A" ],

  # [ 26, "Raichu", "electric", "N/A" ],

  # # [ 26, "Alolan Raichu", "electric", "psychic" ],

  # [ 27, "Sandshrew", "ground", "N/A" ],

  # # [ 27, "Alolan Sandshrew", "ice", "steel" ],

  # [ 28, "Sandslash", "ground", "N/A" ],

  # # [ 28, "Alolan Sandslash", "ice", "steel" ],

  # [ 29, "Nidoran♀", "poison", "N/A" ],
  # [ 30, "Nidorina", "poison", "N/A" ],
  # [ 31, "Nidoqueen", "poison", "ground" ],
  # [ 32, "Nidoran♂", "poison", "N/A" ],
  # [ 33, "Nidorino", "poison", "N/A" ],
  # [ 34, "Nidoking", "poison", "ground" ],
  # [ 35, "Clefairy", "fairy", "N/A" ],
  # [ 36, "Clefable", "fairy", "N/A" ],
  # [ 37, "Vulpix", "fire", "N/A" ],

  # # [ 37, "Alolan Vulpix", "ice", "N/A" ],

  # [ 38, "Ninetales", "fire", "N/A" ],

  # # [ 38, "Alolan Ninetales", "ice", "fairy" ],

  # [ 39, "Jigglypuff", "normal", "fairy" ],
  # [ 40, "Wigglytuff", "normal", "fairy" ],
  # [ 41, "Zubat", "poison", "flying" ],
  # [ 42, "Golbat", "poison", "flying" ],
  # [ 43, "Oddish", "grass", "poison" ],
  # [ 44, "Gloom", "grass", "poison" ],
  # [ 45, "Vileplume", "grass", "poison" ],
  # [ 46, "Paras", "bug", "grass" ],
  # [ 47, "Parasect", "bug", "grass" ],
  # [ 48, "Venonat", "bug", "poison" ],
  # [ 49, "Venomoth", "bug", "poison" ],
  # [ 50, "Diglett", "ground", "N/A" ],

  # # [ 50, "Alolan Diglett", "ground", "steel" ],

  # [ 51, "Dugtrio", "ground", "N/A" ],

  # # [ 51, "Alolan Dugtrio", "ground", "steel" ],

  # [ 52, "Meowth", "normal", "N/A" ],

  # # [ 52, "Alolan Meowth", "dark", "N/A" ],

  # [ 53, "Persian", "normal", "N/A" ],

  # # [ 53, "Alolan Persian", "dark", "N/A" ],

  # [ 54, "Psyduck", "water", "N/A" ],
  # [ 55, "Golduck", "water", "N/A" ],
  # [ 56, "Mankey", "fighting", "N/A" ],
  # [ 57, "Primeape", "fighting", "N/A" ],
  # [ 58, "Growlithe", "fire", "N/A" ],
  # [ 59, "Arcanine", "fire", "N/A" ],
  # [ 60, "Poliwag", "water", "N/A" ],
  # [ 61, "Poliwhirl", "water", "N/A" ],
  # [ 62, "Poliwrath", "water", "fighting" ],
  # [ 63, "Abra", "psychic", "N/A" ],
  # [ 64, "Kadabra", "psychic", "N/A" ],
  # [ 65, "Alakazam", "psychic", "N/A" ],

  # # [ 65, "Mega Alakazam", "psychic", "N/A" ],

  # [ 66, "Machop", "fighting", "N/A" ],
  # [ 67, "Machoke", "fighting", "N/A" ],
  # [ 68, "Machamp", "fighting", "N/A" ],
  # [ 69, "Bellsprout", "grass", "poison" ],
  # [ 70, "Weepinbell", "grass", "poison" ],
  # [ 71, "Victreebel", "grass", "poison" ],
  # [ 72, "Tentacool", "water", "poison" ],
  # [ 73, "Tentacruel", "water", "poison" ],
  # [ 74, "Geodude", "rock", "ground" ],

  # # [ 74, "Alolan Geodude", "rock", "electric" ],

  # [ 75, "Graveler", "rock", "ground" ],

  # # [ 75, "Alolan Graveler", "rock", "electric" ],

  # [ 76, "Golem", "rock", "ground" ],

  # # [ 76, "Alolan Golem", "rock", "electric" ],

  # [ 77, "Ponyta", "fire", "N/A" ],
  # [ 78, "Rapidash", "fire", "N/A" ],
  # [ 79, "Slowpoke", "water", "psychic" ],
  # [ 80, "Slowbro", "water", "psychic" ],

  # # [ 80, "Mega Slowbro", "water", "psychic" ],

  # [ 81, "Magnemite", "electric", "steel" ],
  # [ 82, "Magneton", "electric", "steel" ],
  # [ 83, "Farfetch'd", "normal", "flying" ],
  # [ 84, "Doduo", "normal", "flying" ],
  # [ 85, "Dodrio", "normal", "flying" ],
  # [ 86, "Seel", "water", "N/A" ],
  # [ 87, "Dewgong", "water", "ice" ],
  # [ 88, "Grimer", "poison", "N/A" ],

  # # [ 88, "Alolan Grimer", "poison", "dark" ],

  # [ 89, "Muk", "poison", "N/A" ],

  # # [ 89, "Alolan Muk", "poison", "dark" ],

  # [ 90, "Shellder", "water", "N/A" ],
  # [ 91, "Cloyster", "water", "ice" ],
  # [ 92, "Gastly", "ghost", "poison" ],
  # [ 93, "Haunter", "ghost", "poison" ],
  # [ 94, "Gengar", "ghost", "poison" ],

  # # [ 94, "Mega Gengar", "ghost", "poison" ],

  # [ 95, "Onix", "rock", "ground" ],
  # [ 96, "Drowzee", "psychic", "N/A" ],
  # [ 97, "Hypno", "psychic", "N/A" ],
  # [ 98, "Krabby", "water", "N/A" ],
  # [ 99, "Kingler", "water", "N/A" ],
  # [ 100, "Voltorb", "electric", "N/A" ],
  # [ 101, "Electrode", "electric", "N/A" ],
  # [ 102, "Exeggcute", "grass", "psychic" ],
  # [ 103, "Exeggutor", "grass", "psychic" ],

  # # [ 103, "Alolan Exeggutor", "grass", "dragon" ],

  # [ 104, "Cubone", "ground", "N/A" ],
  # [ 105, "Marowak", "ground", "N/A" ],

  # # [ 105, "Alolan Marowak", "fire", "ghost" ],

  # [ 106, "Hitmonlee", "fighting", "N/A" ],
  # [ 107, "Hitmonchan", "fighting", "N/A" ],
  # [ 108, "Lickitung", "normal", "N/A" ],
  # [ 109, "Koffing", "poison", "N/A" ],
  # [ 110, "Weezing", "poison", "N/A" ],
  # [ 111, "Rhyhorn", "ground", "rock" ],
  # [ 112, "Rhydon", "ground", "rock" ],
  # [ 113, "Chansey", "normal", "N/A" ],
  # [ 114, "Tangela", "grass", "N/A" ],
  # [ 115, "Kangaskhan", "normal", "N/A" ],

  # # [ 115, "Mega Kangaskhan", "normal", "N/A" ],

  # [ 116, "Horsea", "water", "N/A" ],
  # [ 117, "Seadra", "water", "N/A" ],
  # [ 118, "Goldeen", "water", "N/A" ],
  # [ 119, "Seaking", "water", "N/A" ],
  # [ 120, "Staryu", "water", "N/A" ],
  # [ 121, "Starmie", "water", "psychic" ],
  # [ 122, "Mr. Mime", "psychic", "fairy" ],
  # [ 123, "Scyther", "bug", "flying" ],
  # [ 124, "Jynx", "ice", "psychic" ],
  # [ 125, "Electabuzz", "electric", "N/A" ],
  # [ 126, "Magmar", "fire", "N/A" ],
  # [ 127, "Pinsir", "bug", "N/A" ],

  # # [ 127, "Mega Pinsir", "bug", "flying" ],

  # [ 128, "Tauros", "normal", "N/A" ],
  # [ 129, "Magikarp", "water", "N/A" ],
  # [ 130, "Gyarados", "water", "flying" ],

  # # [ 130, "Mega Gyarados", "water", "dark" ],

  # [ 131, "Lapras", "water", "ice" ],
  # [ 132, "Ditto", "normal", "N/A" ],
  # [ 133, "Eevee", "normal", "N/A" ],

  # # [ 133, "Partner Eevee", "normal", "N/A" ],

  # [ 134, "Vaporeon", "water", "N/A" ],
  # [ 135, "Jolteon", "electric", "N/A" ],
  # [ 136, "Flareon", "fire", "N/A" ],
  # [ 137, "Porygon", "normal", "N/A" ],
  # [ 138, "Omanyte", "rock", "water" ],
  # [ 139, "Omastar", "rock", "water" ],
  # [ 140, "Kabuto", "rock", "water" ],
  # [ 141, "Kabutops", "rock", "water" ],
  # [ 142, "Aerodactyl", "rock", "flying" ],

  # # [ 142, "Mega Aerodactyl", "rock", "flying" ],

  # [ 143, "Snorlax", "normal", "N/A" ],
  # [ 144, "Articuno", "ice", "flying" ],
  # [ 145, "Zapdos", "electric", "flying" ],
  # [ 146, "Moltres", "fire", "flying" ],
  # [ 147, "Dratini", "dragon", "N/A" ],
  # [ 148, "Dragonair", "dragon", "N/A" ],
  # [ 149, "Dragonite", "dragon", "flying" ],
  # [ 150, "Mewtwo", "psychic", "N/A" ],

  # # [ 150, "Mega Mewtwo X", "psychic", "fighting" ],
  # # [ 150, "Mega Mewtwo Y", "psychic", "N/A" ],

  # [ 151, "Mew", "psychic", "N/A" ] #,

  # [ 152, "Chikorita", "grass", "N/A" ],
  # [ 153, "Bayleef", "grass", "N/A" ],
  # [ 154, "Meganium", "grass", "N/A" ],
  # [ 155, "Cyndaquil", "fire", "N/A" ],
  # [ 156, "Quilava", "fire", "N/A" ],
  # [ 157, "Typhlosion", "fire", "N/A" ],
  # [ 158, "Totodile", "water", "N/A" ],
  # [ 159, "Croconaw", "water", "N/A" ],
  # [ 160, "Feraligatr", "water", "N/A" ],
  # [ 161, "Sentret", "normal", "N/A" ],
  # [ 162, "Furret", "normal", "N/A" ],
  # [ 163, "Hoothoot", "normal", "flying" ],
  # [ 164, "Noctowl", "normal", "flying" ],
  # [ 165, "Ledyba", "bug", "flying" ],
  # [ 166, "Ledian", "bug", "flying" ],
  # [ 167, "Spinarak", "bug", "poison" ],
  # [ 168, "Ariados", "bug", "poison" ],
  # [ 169, "Crobat", "poison", "flying" ],
  # [ 170, "Chinchou", "water", "electric" ],
  # [ 171, "Lanturn", "water", "electric" ],
  # [ 172, "Pichu", "electric", "N/A" ],
  # [ 173, "Cleffa", "fairy", "N/A" ],
  # [ 174, "Igglybuff", "normal", "fairy" ],
  # [ 175, "Togepi", "fairy", "N/A" ],
  # [ 176, "Togetic", "fairy", "flying" ],
  # [ 177, "Natu", "psychic", "flying" ],
  # [ 178, "Xatu", "psychic", "flying" ],
  # [ 179, "Mareep", "electric", "N/A" ],
  # [ 180, "Flaaffy", "electric", "N/A" ],
  # [ 181, "Ampharos", "electric", "N/A" ],
  # [ 181, "Mega Ampharos", "electric", "dragon" ],
  # [ 182, "Bellossom", "grass", "N/A" ],
  # [ 183, "Marill", "water", "fairy" ],
  # [ 184, "Azumarill", "water", "fairy" ],
  # [ 185, "Sudowoodo", "rock", "N/A" ],
  # [ 186, "Politoed", "water", "N/A" ],
  # [ 187, "Hoppip", "grass", "flying" ],
  # [ 188, "Skiploom", "grass", "flying" ],
  # [ 189, "Jumpluff", "grass", "flying" ],
  # [ 190, "Aipom", "normal", "N/A" ],
  # [ 191, "Sunkern", "grass", "N/A" ],
  # [ 192, "Sunflora", "grass", "N/A" ],
  # [ 193, "Yanma", "bug", "flying" ],
  # [ 194, "Wooper", "water", "ground" ],
  # [ 195, "Quagsire", "water", "ground" ],
  # [ 196, "Espeon", "psychic", "N/A" ],
  # [ 197, "Umbreon", "dark", "N/A" ],
  # [ 198, "Murkrow", "dark", "flying" ],
  # [ 199, "Slowking", "water", "psychic" ],
  # [ 200, "Misdreavus", "ghost", "N/A" ],
  # [ 201, "Unown", "psychic", "N/A" ],
  # [ 202, "Wobbuffet", "psychic", "N/A" ],
  # [ 203, "Girafarig", "normal", "psychic" ],
  # [ 204, "Pineco", "bug", "N/A" ],
  # [ 205, "Forretress", "bug", "steel" ],
  # [ 206, "Dunsparce", "normal", "N/A" ],
  # [ 207, "Gligar", "ground", "flying" ],
  # [ 208, "Steelix", "steel", "ground" ],
  # [ 208, "Mega Steelix", "steel", "ground" ],
  # [ 209, "Snubbull", "fairy", "N/A" ],
  # [ 210, "Granbull", "fairy", "N/A" ],
  # [ 211, "Qwilfish", "water", "poison" ],
  # [ 212, "Scizor", "bug", "steel" ],
  # [ 212, "Mega Scizor", "bug", "steel" ],
  # [ 213, "Shuckle", "bug", "rock" ],
  # [ 214, "Heracross", "bug", "fighting" ],
  # [ 214, "Mega Heracross", "bug", "fighting" ],
  # [ 215, "Sneasel", "dark", "ice" ],
  # [ 216, "Teddiursa", "normal", "N/A" ],
  # [ 217, "Ursaring", "normal", "N/A" ],
  # [ 218, "Slugma", "fire", "N/A" ],
  # [ 219, "Magcargo", "fire", "rock" ],
  # [ 220, "Swinub", "ice", "ground" ],
  # [ 221, "Piloswine", "ice", "ground" ],
  # [ 222, "Corsola", "water", "rock" ],
  # [ 223, "Remoraid", "water", "N/A" ],
  # [ 224, "Octillery", "water", "N/A" ],
  # [ 225, "Delibird", "ice", "flying" ],
  # [ 226, "Mantine", "water", "flying" ],
  # [ 227, "Skarmory", "steel", "flying" ],
  # [ 228, "Houndour", "dark", "fire" ],
  # [ 229, "Houndoom", "dark", "fire" ],
  # [ 229, "Mega Houndoom", "dark", "fire" ],
  # [ 230, "Kingdra", "water", "dragon" ],
  # [ 231, "Phanpy", "ground", "N/A" ],
  # [ 232, "Donphan", "ground", "N/A" ],
  # [ 233, "Porygon2", "normal", "N/A" ],
  # [ 234, "Stantler", "normal", "N/A" ],
  # [ 235, "Smeargle", "normal", "N/A" ],
  # [ 236, "Tyrogue", "fighting", "N/A" ],
  # [ 237, "Hitmontop", "fighting", "N/A" ],
  # [ 238, "Smoochum", "ice", "psychic" ],
  # [ 239, "Elekid", "electric", "N/A" ],
  # [ 240, "Magby", "fire", "N/A" ],
  # [ 241, "Miltank", "normal", "N/A" ],
  # [ 242, "Blissey", "normal", "N/A" ],
  # [ 243, "Raikou", "electric", "N/A" ],
  # [ 244, "Entei", "fire", "N/A" ],
  # [ 245, "Suicune", "water", "N/A" ],
  # [ 246, "Larvitar", "rock", "ground" ],
  # [ 247, "Pupitar", "rock", "ground" ],
  # [ 248, "Tyranitar", "rock", "dark" ],
  # [ 248, "Mega Tyranitar", "rock", "dark" ],
  # [ 249, "Lugia", "psychic", "flying" ],
  # [ 250, "Ho-oh", "fire", "flying" ],
  # [ 251, "Celebi", "psychic", "grass" ],
  # [ 252, "Treecko", "grass", "N/A" ],
  # [ 253, "Grovyle", "grass", "N/A" ],
  # [ 254, "Sceptile", "grass", "N/A" ],
  # [ 254, "Mega Sceptile", "grass", "dragon" ],
  # [ 255, "Torchic", "fire", "N/A" ],
  # [ 256, "Combusken", "fire", "fighting" ],
  # [ 257, "Blaziken", "fire", "fighting" ],
  # [ 257, "Mega Blaziken", "fire", "fighting" ],
  # [ 258, "Mudkip", "water", "N/A" ],
  # [ 259, "Marshtomp", "water", "ground" ],
  # [ 260, "Swampert", "water", "ground" ],
  # [ 260, "Mega Swampert", "water", "ground" ],
  # [ 261, "Poochyena", "dark", "N/A" ],
  # [ 262, "Mightyena", "dark", "N/A" ],
  # [ 263, "Zigzagoon", "normal", "N/A" ],
  # [ 264, "Linoone", "normal", "N/A" ],
  # [ 265, "Wurmple", "bug", "N/A" ],
  # [ 266, "Silcoon", "bug", "N/A" ],
  # [ 267, "Beautifly", "bug", "flying" ],
  # [ 268, "Cascoon", "bug", "N/A" ],
  # [ 269, "Dustox", "bug", "poison" ],
  # [ 270, "Lotad", "water", "grass" ],
  # [ 271, "Lombre", "water", "grass" ],
  # [ 272, "Ludicolo", "water", "grass" ],
  # [ 273, "Seedot", "grass", "N/A" ],
  # [ 274, "Nuzleaf", "grass", "dark" ],
  # [ 275, "Shiftry", "grass", "dark" ],
  # [ 276, "Taillow", "normal", "flying" ],
  # [ 277, "Swellow", "normal", "flying" ],
  # [ 278, "Wingull", "water", "flying" ],
  # [ 279, "Pelipper", "water", "flying" ],
  # [ 280, "Ralts", "psychic", "fairy" ],
  # [ 281, "Kirlia", "psychic", "fairy" ],
  # [ 282, "Gardevoir", "psychic", "fairy" ],
  # [ 282, "Mega Gardevoir", "psychic", "fairy" ],
  # [ 283, "Surskit", "bug", "water" ],
  # [ 284, "Masquerain", "bug", "flying" ],
  # [ 285, "Shroomish", "grass", "N/A" ],
  # [ 286, "Breloom", "grass", "fighting" ],
  # [ 287, "Slakoth", "normal", "N/A" ],
  # [ 288, "Vigoroth", "normal", "N/A" ],
  # [ 289, "Slaking", "normal", "N/A" ],
  # [ 290, "Nincada", "bug", "ground" ],
  # [ 291, "Ninjask", "bug", "flying" ],
  # [ 292, "Shedinja", "bug", "ghost" ],
  # [ 293, "Whismur", "normal", "N/A" ],
  # [ 294, "Loudred", "normal", "N/A" ],
  # [ 295, "Exploud", "normal", "N/A" ],
  # [ 296, "Makuhita", "fighting", "N/A" ],
  # [ 297, "Hariyama", "fighting", "N/A" ],
  # [ 298, "Azurill", "normal", "fairy" ],
  # [ 299, "Nosepass", "rock", "N/A" ],
  # [ 300, "Skitty", "normal", "N/A" ],
  # [ 301, "Delcatty", "normal", "N/A" ],
  # [ 302, "Sableye", "dark", "ghost" ],
  # [ 302, "Mega Sableye", "dark", "ghost" ],
  # [ 303, "Mawile", "steel", "fairy" ],
  # [ 303, "Mega Mawile", "steel", "fairy" ],
  # [ 304, "Aron", "steel", "rock" ],
  # [ 305, "Lairon", "steel", "rock" ],
  # [ 306, "Aggron", "steel", "rock" ],
  # [ 306, "Mega Aggron", "steel", "N/A" ],
  # [ 307, "Meditite", "fighting", "psychic" ],
  # [ 308, "Medicham", "fighting", "psychic" ],
  # [ 308, "Mega Medicham", "fighting", "psychic" ],
  # [ 309, "Electrike", "electric", "N/A" ],
  # [ 310, "Manectric", "electric", "N/A" ],
  # [ 310, "Mega Manectric", "electric", "N/A" ],
  # [ 311, "Plusle", "electric", "N/A" ],
  # [ 312, "Minun", "electric", "N/A" ],
  # [ 313, "Volbeat", "bug", "N/A" ],
  # [ 314, "Illumise", "bug", "N/A" ],
  # [ 315, "Roselia", "grass", "poison" ],
  # [ 316, "Gulpin", "poison", "N/A" ],
  # [ 317, "Swalot", "poison", "N/A" ],
  # [ 318, "Carvanha", "water", "dark" ],
  # [ 319, "Sharpedo", "water", "dark" ],
  # [ 319, "Mega Sharpedo", "water", "dark" ],
  # [ 320, "Wailmer", "water", "N/A" ],
  # [ 321, "Wailord", "water", "N/A" ],
  # [ 322, "Numel", "fire", "ground" ],
  # [ 323, "Camerupt", "fire", "ground" ],
  # [ 323, "Mega Camerupt", "fire", "ground" ],
  # [ 324, "Torkoal", "fire", "N/A" ],
  # [ 325, "Spoink", "psychic", "N/A" ],
  # [ 326, "Grumpig", "psychic", "N/A" ],
  # [ 327, "Spinda", "normal", "N/A" ],
  # [ 328, "Trapinch", "ground", "N/A" ],
  # [ 329, "Vibrava", "ground", "dragon" ],
  # [ 330, "Flygon", "ground", "dragon" ],
  # [ 331, "Cacnea", "grass", "N/A" ],
  # [ 332, "Cacturne", "grass", "dark" ],
  # [ 333, "Swablu", "normal", "flying" ],
  # [ 334, "Altaria", "dragon", "flying" ],
  # [ 334, "Mega Altaria", "dragon", "fairy" ],
  # [ 335, "Zangoose", "normal", "N/A" ],
  # [ 336, "Seviper", "poison", "N/A" ],
  # [ 337, "Lunatone", "rock", "psychic" ],
  # [ 338, "Solrock", "rock", "psychic" ],
  # [ 339, "Barboach", "water", "ground" ],
  # [ 340, "Whiscash", "water", "ground" ],
  # [ 341, "Corphish", "water", "N/A" ],
  # [ 342, "Crawdaunt", "water", "dark" ],
  # [ 343, "Baltoy", "ground", "psychic" ],
  # [ 344, "Claydol", "ground", "psychic" ],
  # [ 345, "Lileep", "rock", "grass" ],
  # [ 346, "Cradily", "rock", "grass" ],
  # [ 347, "Anorith", "rock", "bug" ],
  # [ 348, "Armaldo", "rock", "bug" ],
  # [ 349, "Feebas", "water", "N/A" ],
  # [ 350, "Milotic", "water", "N/A" ],
  # [ 351, "Castform", "normal", "N/A" ],
  # [ 351, "Sunny Form", "fire", "N/A" ],
  # [ 351, "Rainy Form", "water", "N/A" ],
  # [ 351, "Snowy Form", "ice", "N/A" ],
  # [ 352, "Kecleon", "normal", "N/A" ],
  # [ 353, "Shuppet", "ghost", "N/A" ],
  # [ 354, "Banette", "ghost", "N/A" ],
  # [ 354, "Mega Banette", "ghost", "N/A" ],
  # [ 355, "Duskull", "ghost", "N/A" ],
  # [ 356, "Dusclops", "ghost", "N/A" ],
  # [ 357, "Tropius", "grass", "flying" ],
  # [ 358, "Chimecho", "psychic", "N/A" ],
  # [ 359, "Absol", "dark", "N/A" ],
  # [ 359, "Mega Absol", "dark", "N/A" ],
  # [ 360, "Wynaut", "psychic", "N/A" ],
  # [ 361, "Snorunt", "ice", "N/A" ],
  # [ 362, "Glalie", "ice", "N/A" ],
  # [ 362, "Mega Glalie", "ice", "N/A" ],
  # [ 363, "Spheal", "ice", "water" ],
  # [ 364, "Sealeo", "ice", "water" ],
  # [ 365, "Walrein", "ice", "water" ],
  # [ 366, "Clamperl", "water", "N/A" ],
  # [ 367, "Huntail", "water", "N/A" ],
  # [ 368, "Gorebyss", "water", "N/A" ],
  # [ 369, "Relicanth", "water", "rock" ],
  # [ 370, "Luvdisc", "water", "N/A" ],
  # [ 371, "Bagon", "dragon", "N/A" ],
  # [ 372, "Shelgon", "dragon", "N/A" ],
  # [ 373, "Salamence", "dragon", "flying" ],
  # [ 373, "Mega Salamence", "dragon", "flying" ],
  # [ 374, "Beldum", "steel", "psychic" ],
  # [ 375, "Metang", "steel", "psychic" ],
  # [ 376, "Metagross", "steel", "psychic" ],
  # [ 376, "Mega Metagross", "steel", "psychic" ],
  # [ 377, "Regirock", "rock", "N/A" ],
  # [ 378, "Regice", "ice", "N/A" ],
  # [ 379, "Registeel", "steel", "N/A" ],
  # [ 380, "Latias", "dragon", "psychic" ],
  # [ 380, "Mega Latias", "dragon", "psychic" ],
  # [ 381, "Latios", "dragon", "psychic" ],
  # [ 381, "Mega Latios", "dragon", "psychic" ],
  # [ 382, "Kyogre", "water", "N/A" ],
  # [ 382, "Primal Kyogre", "water", "N/A" ],
  # [ 383, "Groudon", "ground", "N/A" ],
  # [ 383, "Primal Groudon", "ground", "fire" ],
  # [ 384, "Rayquaza", "dragon", "flying" ],
  # [ 384, "Mega Rayquaza", "dragon", "flying" ],
  # [ 385, "Jirachi", "steel", "psychic" ],
  # [ 386, "Deoxys Normal Form", "psychic", "N/A" ],
  # [ 386, "Deoxys Attack Form", "psychic", "N/A" ],
  # [ 386, "Deoxys Defense Form", "psychic", "N/A" ],
  # [ 386, "Deoxys Speed Form", "psychic", "N/A" ],
  # [ 387, "Turtwig", "grass", "N/A" ],
  # [ 388, "Grotle", "grass", "N/A" ],
  # [ 389, "Torterra", "grass", "ground" ],
  # [ 390, "Chimchar", "fire", "N/A" ],
  # [ 391, "Monferno", "fire", "fighting" ],
  # [ 392, "Infernape", "fire", "fighting" ],
  # [ 393, "Piplup", "water", "N/A" ],
  # [ 394, "Prinplup", "water", "N/A" ],
  # [ 395, "Empoleon", "water", "steel" ],
  # [ 396, "Starly", "normal", "flying" ],
  # [ 397, "Staravia", "normal", "flying" ],
  # [ 398, "Staraptor", "normal", "flying" ],
  # [ 399, "Bidoof", "normal", "N/A" ],
  # [ 400, "Bibarel", "normal", "water" ],
  # [ 401, "Kricketot", "bug", "N/A" ],
  # [ 402, "Kricketune", "bug", "N/A" ],
  # [ 403, "Shinx", "electric", "N/A" ],
  # [ 404, "Luxio", "electric", "N/A" ],
  # [ 405, "Luxray", "electric", "N/A" ],
  # [ 406, "Budew", "grass", "poison" ],
  # [ 407, "Roserade", "grass", "poison" ],
  # [ 408, "Cranidos", "rock", "N/A" ],
  # [ 409, "Rampardos", "rock", "N/A" ],
  # [ 410, "Shieldon", "rock", "steel" ],
  # [ 411, "Bastiodon", "rock", "steel" ],
  # [ 412, "Burmy", "bug", "N/A" ],
  # [ 413, "Wormadam Plant Cloak", "bug", "grass" ],
  # [ 413, "Wormadam Sandy Cloak", "bug", "ground" ],
  # [ 413, "Wormadam Trash Cloak", "bug", "steel" ],
  # [ 414, "Mothim", "bug", "flying" ],
  # [ 415, "Combee", "bug", "flying" ],
  # [ 416, "Vespiquen", "bug", "flying" ],
  # [ 417, "Pachirisu", "electric", "N/A" ],
  # [ 418, "Buizel", "water", "N/A" ],
  # [ 419, "Floatzel", "water", "N/A" ],
  # [ 420, "Cherubi", "grass", "N/A" ],
  # [ 421, "Cherrim", "grass", "N/A" ],
  # [ 422, "Shellos", "water", "N/A" ],
  # [ 423, "Gastrodon", "water", "ground" ],
  # [ 424, "Ambipom", "normal", "N/A" ],
  # [ 425, "Drifloon", "ghost", "flying" ],
  # [ 426, "Drifblim", "ghost", "flying" ],
  # [ 427, "Buneary", "normal", "N/A" ],
  # [ 428, "Lopunny", "normal", "N/A" ],
  # [ 428, "Mega Lopunny", "normal", "fighting" ],
  # [ 429, "Mismagius", "ghost", "N/A" ],
  # [ 430, "Honchkrow", "dark", "flying" ],
  # [ 431, "Glameow", "normal", "N/A" ],
  # [ 432, "Purugly", "normal", "N/A" ],
  # [ 433, "Chingling", "psychic", "N/A" ],
  # [ 434, "Stunky", "poison", "dark" ],
  # [ 435, "Skuntank", "poison", "dark" ],
  # [ 436, "Bronzor", "steel", "psychic" ],
  # [ 437, "Bronzong", "steel", "psychic" ],
  # [ 438, "Bonsly", "rock", "N/A" ],
  # [ 439, "Mime Jr.", "psychic", "fairy" ],
  # [ 440, "Happiny", "normal", "N/A" ],
  # [ 441, "Chatot", "normal", "flying" ],
  # [ 442, "Spiritomb", "ghost", "dark" ],
  # [ 443, "Gible", "dragon", "ground" ],
  # [ 444, "Gabite", "dragon", "ground" ],
  # [ 445, "Garchomp", "dragon", "ground" ],
  # [ 445, "Mega Garchomp", "dragon", "ground" ],
  # [ 446, "Munchlax", "normal", "N/A" ],
  # [ 447, "Riolu", "fighting", "N/A" ],
  # [ 448, "Lucario", "fighting", "steel" ],
  # [ 448, "Mega Lucario", "fighting", "steel" ],
  # [ 449, "Hippopotas", "ground", "N/A" ],
  # [ 450, "Hippowdon", "ground", "N/A" ],
  # [ 451, "Skorupi", "poison", "bug" ],
  # [ 452, "Drapion", "poison", "dark" ],
  # [ 453, "Croagunk", "poison", "fighting" ],
  # [ 454, "Toxicroak", "poison", "fighting" ],
  # [ 455, "Carnivine", "grass", "N/A" ],
  # [ 456, "Finneon", "water", "N/A" ],
  # [ 457, "Lumineon", "water", "N/A" ],
  # [ 458, "Mantyke", "water", "flying" ],
  # [ 459, "Snover", "grass", "ice" ],
  # [ 460, "Abomasnow", "grass", "ice" ],
  # [ 460, "Mega Abomasnow", "grass", "ice" ],
  # [ 461, "Weavile", "dark", "ice" ],
  # [ 462, "Magnezone", "electric", "steel" ],
  # [ 463, "Lickilicky", "normal", "N/A" ],
  # [ 464, "Rhyperior", "ground", "rock" ],
  # [ 465, "Tangrowth", "grass", "N/A" ],
  # [ 466, "Electivire", "electric", "N/A" ],
  # [ 467, "Magmortar", "fire", "N/A" ],
  # [ 468, "Togekiss", "fairy", "flying" ],
  # [ 469, "Yanmega", "bug", "flying" ],
  # [ 470, "Leafeon", "grass", "N/A" ],
  # [ 471, "Glaceon", "ice", "N/A" ],
  # [ 472, "Gliscor", "ground", "flying" ],
  # [ 473, "Mamoswine", "ice", "ground" ],
  # [ 474, "Porygon-Z", "normal", "N/A" ],
  # [ 475, "Gallade", "psychic", "fighting" ],
  # [ 475, "Mega Gallade", "psychic", "fighting" ],
  # [ 476, "Probopass", "rock", "steel" ],
  # [ 477, "Dusknoir", "ghost", "N/A" ],
  # [ 478, "Froslass", "ice", "ghost" ],
  # [ 479, "Rotom", "electric", "ghost" ],
  # [ 479, "Heat Rotom", "electric", "fire" ],
  # [ 479, "Wash Rotom", "electric", "water" ],
  # [ 479, "Frost Rotom", "electric", "ice" ],
  # [ 479, "Fan Rotom", "electric", "flying" ],
  # [ 479, "Mow Rotom", "electric", "grass" ],
  # [ 480, "Uxie", "psychic", "N/A" ],
  # [ 481, "Mesprit", "psychic", "N/A" ],
  # [ 482, "Azelf", "psychic", "N/A" ],
  # [ 483, "Dialga", "steel", "dragon" ],
  # [ 484, "Palkia", "water", "dragon" ],
  # [ 485, "Heatran", "fire", "steel" ],
  # [ 486, "Regigigas", "normal", "N/A" ],
  # [ 487, "Giratina Altered Form", "ghost", "dragon" ],
  # [ 487, "Giratina Origin Form", "ghost", "dragon" ],
  # [ 488, "Cresselia", "psychic", "N/A" ],
  # [ 489, "Phione", "water", "N/A" ],
  # [ 490, "Manaphy", "water", "N/A" ],
  # [ 491, "Darkrai", "dark", "N/A" ],
  # [ 492, "Shaymin Land Form", "grass", "N/A" ],
  # [ 492, "Shaymin Sky Form", "grass", "flying" ],
  # [ 493, "Arceus", "normal", "N/A" ],
  # [ 494, "Victini", "psychic", "fire" ],
  # [ 495, "Snivy", "grass", "N/A" ],
  # [ 496, "Servine", "grass", "N/A" ],
  # [ 497, "Serperior", "grass", "N/A" ],
  # [ 498, "Tepig", "fire", "N/A" ],
  # [ 499, "Pignite", "fire", "fighting" ],
  # [ 500, "Emboar", "fire", "fighting" ],
  # [ 501, "Oshawott", "water", "N/A" ],
  # [ 502, "Dewott", "water", "N/A" ],
  # [ 503, "Samurott", "water", "N/A" ],
  # [ 504, "Patrat", "normal", "N/A" ],
  # [ 505, "Watchog", "normal", "N/A" ],
  # [ 506, "Lillipup", "normal", "N/A" ],
  # [ 507, "Herdier", "normal", "N/A" ],
  # [ 508, "Stoutland", "normal", "N/A" ],
  # [ 509, "Purrloin", "dark", "N/A" ],
  # [ 510, "Liepard", "dark", "N/A" ],
  # [ 511, "Pansage", "grass", "N/A" ],
  # [ 512, "Simisage", "grass", "N/A" ],
  # [ 513, "Pansear", "fire", "N/A" ],
  # [ 514, "Simisear", "fire", "N/A" ],
  # [ 515, "Panpour", "water", "N/A" ],
  # [ 516, "Simipour", "water", "N/A" ],
  # [ 517, "Munna", "psychic", "N/A" ],
  # [ 518, "Musharna", "psychic", "N/A" ],
  # [ 519, "Pidove", "normal", "flying" ],
  # [ 520, "Tranquill", "normal", "flying" ],
  # [ 521, "Unfezant", "normal", "flying" ],
  # [ 522, "Blitzle", "electric", "N/A" ],
  # [ 523, "Zebstrika", "electric", "N/A" ],
  # [ 524, "Roggenrola", "rock", "N/A" ],
  # [ 525, "Boldore", "rock", "N/A" ],
  # [ 526, "Gigalith", "rock", "N/A" ],
  # [ 527, "Woobat", "psychic", "flying" ],
  # [ 528, "Swoobat", "psychic", "flying" ],
  # [ 529, "Drilbur", "ground", "N/A" ],
  # [ 530, "Excadrill", "ground", "steel" ],
  # [ 531, "Audino", "normal", "N/A" ],
  # [ 531, "Mega Audino", "normal", "fairy" ],
  # [ 532, "Timburr", "fighting", "N/A" ],
  # [ 533, "Gurdurr", "fighting", "N/A" ],
  # [ 534, "Conkeldurr", "fighting", "N/A" ],
  # [ 535, "Tympole", "water", "N/A" ],
  # [ 536, "Palpitoad", "water", "ground" ],
  # [ 537, "Seismitoad", "water", "ground" ],
  # [ 538, "Throh", "fighting", "N/A" ],
  # [ 539, "Sawk", "fighting", "N/A" ],
  # [ 540, "Sewaddle", "bug", "grass" ],
  # [ 541, "Swadloon", "bug", "grass" ],
  # [ 542, "Leavanny", "bug", "grass" ],
  # [ 543, "Venipede", "bug", "poison" ],
  # [ 544, "Whirlipede", "bug", "poison" ],
  # [ 545, "Scolipede", "bug", "poison" ],
  # [ 546, "Cottonee", "grass", "fairy" ],
  # [ 547, "Whimsicott", "grass", "fairy" ],
  # [ 548, "Petilil", "grass", "N/A" ],
  # [ 549, "Lilligant", "grass", "N/A" ],
  # [ 550, "Basculin Red-Striped Form", "water", "N/A" ],
  # [ 550, "Basculin Blue-Striped Form", "water", "N/A" ],
  # [ 551, "Sandile", "ground", "dark" ],
  # [ 552, "Krokorok", "ground", "dark" ],
  # [ 553, "Krookodile", "ground", "dark" ],
  # [ 554, "Darumaka", "fire", "N/A" ],
  # [ 555, "Darmanitan Standard Mode", "fire", "N/A" ],
  # [ 555, "Darmanitan Zen Mode", "fire", "psychic" ],
  # [ 556, "Maractus", "grass", "N/A" ],
  # [ 557, "Dwebble", "bug", "rock" ],
  # [ 558, "Crustle", "bug", "rock" ],
  # [ 559, "Scraggy", "dark", "fighting" ],
  # [ 560, "Scrafty", "dark", "fighting" ],
  # [ 561, "Sigilyph", "psychic", "flying" ],
  # [ 562, "Yamask", "ghost", "N/A" ],
  # [ 563, "Cofagrigus", "ghost", "N/A" ],
  # [ 564, "Tirtouga", "water", "rock" ],
  # [ 565, "Carracosta", "water", "rock" ],
  # [ 566, "Archen", "rock", "flying" ],
  # [ 567, "Archeops", "rock", "flying" ],
  # [ 568, "Trubbish", "poison", "N/A" ],
  # [ 569, "Garbodor", "poison", "N/A" ],
  # [ 570, "Zorua", "dark", "N/A" ],
  # [ 571, "Zoroark", "dark", "N/A" ],
  # [ 572, "Minccino", "normal", "N/A" ],
  # [ 573, "Cinccino", "normal", "N/A" ],
  # [ 574, "Gothita", "psychic", "N/A" ],
  # [ 575, "Gothorita", "psychic", "N/A" ],
  # [ 576, "Gothitelle", "psychic", "N/A" ],
  # [ 577, "Solosis", "psychic", "N/A" ],
  # [ 578, "Duosion", "psychic", "N/A" ],
  # [ 579, "Reuniclus", "psychic", "N/A" ],
  # [ 580, "Ducklett", "water", "flying" ],
  # [ 581, "Swanna", "water", "flying" ],
  # [ 582, "Vanillite", "ice", "N/A" ],
  # [ 583, "Vanillish", "ice", "N/A" ],
  # [ 584, "Vanilluxe", "ice", "N/A" ],
  # [ 585, "Deerling", "normal", "grass" ],
  # [ 586, "Sawsbuck", "normal", "grass" ],
  # [ 587, "Emolga", "electric", "flying" ],
  # [ 588, "Karrablast", "bug", "N/A" ],
  # [ 589, "Escavalier", "bug", "steel" ],
  # [ 590, "Foongus", "grass", "poison" ],
  # [ 591, "Amoonguss", "grass", "poison" ],
  # [ 592, "Frillish", "water", "ghost" ],
  # [ 593, "Jellicent", "water", "ghost" ],
  # [ 594, "Alomomola", "water", "N/A" ],
  # [ 595, "Joltik", "bug", "electric" ],
  # [ 596, "Galvantula", "bug", "electric" ],
  # [ 597, "Ferroseed", "grass", "steel" ],
  # [ 598, "Ferrothorn", "grass", "steel" ],
  # [ 599, "Klink", "steel", "N/A" ],
  # [ 600, "Klang", "steel", "N/A" ],
  # [ 601, "Klinklang", "steel", "N/A" ],
  # [ 602, "Tynamo", "electric", "N/A" ],
  # [ 603, "Eelektrik", "electric", "N/A" ],
  # [ 604, "Eelektross", "electric", "N/A" ],
  # [ 605, "Elgyem", "psychic", "N/A" ],
  # [ 606, "Beheeyem", "psychic", "N/A" ],
  # [ 607, "Litwick", "ghost", "fire" ],
  # [ 608, "Lampent", "ghost", "fire" ],
  # [ 609, "Chandelure", "ghost", "fire" ],
  # [ 610, "Axew", "dragon", "N/A" ],
  # [ 611, "Fraxure", "dragon", "N/A" ],
  # [ 612, "Haxorus", "dragon", "N/A" ],
  # [ 613, "Cubchoo", "ice", "N/A" ],
  # [ 614, "Beartic", "ice", "N/A" ],
  # [ 615, "Cryogonal", "ice", "N/A" ],
  # [ 616, "Shelmet", "bug", "N/A" ],
  # [ 617, "Accelgor", "bug", "N/A" ],
  # [ 618, "Stunfisk", "ground", "electric" ],
  # [ 619, "Mienfoo", "fighting", "N/A" ],
  # [ 620, "Mienshao", "fighting", "N/A" ],
  # [ 621, "Druddigon", "dragon", "N/A" ],
  # [ 622, "Golett", "ground", "ghost" ],
  # [ 623, "Golurk", "ground", "ghost" ],
  # [ 624, "Pawniard", "dark", "steel" ],
  # [ 625, "Bisharp", "dark", "steel" ],
  # [ 626, "Bouffalant", "normal", "N/A" ],
  # [ 627, "Rufflet", "normal", "flying" ],
  # [ 628, "Braviary", "normal", "flying" ],
  # [ 629, "Vullaby", "dark", "flying" ],
  # [ 630, "Mandibuzz", "dark", "flying" ],
  # [ 631, "Heatmor", "fire", "N/A" ],
  # [ 632, "Durant", "bug", "steel" ],
  # [ 633, "Deino", "dark", "dragon" ],
  # [ 634, "Zweilous", "dark", "dragon" ],
  # [ 635, "Hydreigon", "dark", "dragon" ],
  # [ 636, "Larvesta", "bug", "fire" ],
  # [ 637, "Volcarona", "bug", "fire" ],
  # [ 638, "Cobalion", "steel", "fighting" ],
  # [ 639, "Terrakion", "rock", "fighting" ],
  # [ 640, "Virizion", "grass", "fighting" ],
  # [ 641, "Tornadus Incarnate Form", "flying", "N/A" ],
  # [ 641, "Tornadus Therian Form", "flying", "N/A" ],
  # [ 642, "Thundurus Incarnate Form", "electric", "flying" ],
  # [ 642, "Thundurus Therian Form", "electric", "flying" ],
  # [ 643, "Reshiram", "dragon", "fire" ],
  # [ 644, "Zekrom", "dragon", "electric" ],
  # [ 645, "Landorus Incarnate Form", "ground", "flying" ],
  # [ 645, "Landorus Therian Form", "ground", "flying" ],
  # [ 646, "Kyurem", "dragon", "ice" ],
  # [ 646, "Kyurem Black Kyurem", "dragon", "ice" ],
  # [ 646, "Kyurem White Kyurem", "dragon", "ice" ],
  # [ 647, "Keldeo Ordinary Form", "water", "fighting" ],
  # [ 647, "Keldeo Resolute Form", "water", "fighting" ],
  # [ 648, "Meloetta Aria Form", "normal", "psychic" ],
  # [ 648, "Meloetta Pirouette Form", "normal", "fighting" ],
  # [ 649, "Genesect", "bug", "steel" ],
  # [ 650, "Chespin", "grass", "N/A" ],
  # [ 651, "Quilladin", "grass", "N/A" ],
  # [ 652, "Chesnaught", "grass", "fighting" ],
  # [ 653, "Fennekin", "fire", "N/A" ],
  # [ 654, "Braixen", "fire", "N/A" ],
  # [ 655, "Delphox", "fire", "psychic" ],
  # [ 656, "Froakie", "water", "N/A" ],
  # [ 657, "Frogadier", "water", "N/A" ],
  # [ 658, "Greninja", "water", "dark" ],
  # [ 658, "Ash-Greninja", "water", "dark" ],
  # [ 659, "Bunnelby", "normal", "N/A" ],
  # [ 660, "Diggersby", "normal", "ground" ],
  # [ 661, "Fletchling", "normal", "flying" ],
  # [ 662, "Fletchinder", "fire", "flying" ],
  # [ 663, "Talonflame", "fire", "flying" ],
  # [ 664, "Scatterbug", "bug", "N/A" ],
  # [ 665, "Spewpa", "bug", "N/A" ],
  # [ 666, "Vivillon", "bug", "flying" ],
  # [ 667, "Litleo", "fire", "normal" ],
  # [ 668, "Pyroar", "fire", "normal" ],
  # [ 669, "Flabébé", "fairy", "N/A" ],
  # [ 670, "Floette", "fairy", "N/A" ],
  # [ 671, "Florges", "fairy", "N/A" ],
  # [ 672, "Skiddo", "grass", "N/A" ],
  # [ 673, "Gogoat", "grass", "N/A" ],
  # [ 674, "Pancham", "fighting", "N/A" ],
  # [ 675, "Pangoro", "fighting", "dark" ],
  # [ 676, "Furfrou", "normal", "N/A" ],
  # [ 677, "Espurr", "psychic", "N/A" ],
  # [ 678, "Meowstic Male", "psychic", "N/A" ],
  # [ 678, "Meowstic Female", "psychic", "N/A" ],
  # [ 679, "Honedge", "steel", "ghost" ],
  # [ 680, "Doublade", "steel", "ghost" ],
  # [ 681, "Aegislash Blade Form", "steel", "ghost" ],
  # [ 681, "Aegislash Shield Form", "steel", "ghost" ],
  # [ 682, "Spritzee", "fairy", "N/A" ],
  # [ 683, "Aromatisse", "fairy", "N/A" ],
  # [ 684, "Swirlix", "fairy", "N/A" ],
  # [ 685, "Slurpuff", "fairy", "N/A" ],
  # [ 686, "Inkay", "dark", "psychic" ],
  # [ 687, "Malamar", "dark", "psychic" ],
  # [ 688, "Binacle", "rock", "water" ],
  # [ 689, "Barbaracle", "rock", "water" ],
  # [ 690, "Skrelp", "poison", "water" ],
  # [ 691, "Dragalge", "poison", "dragon" ],
  # [ 692, "Clauncher", "water", "N/A" ],
  # [ 693, "Clawitzer", "water", "N/A" ],
  # [ 694, "Helioptile", "electric", "normal" ],
  # [ 695, "Heliolisk", "electric", "normal" ],
  # [ 696, "Tyrunt", "rock", "dragon" ],
  # [ 697, "Tyrantrum", "rock", "dragon" ],
  # [ 698, "Amaura", "rock", "ice" ],
  # [ 699, "Aurorus", "rock", "ice" ],
  # [ 700, "Sylveon", "fairy", "N/A" ],
  # [ 701, "Hawlucha", "fighting", "flying" ],
  # [ 702, "Dedenne", "electric", "fairy" ],
  # [ 703, "Carbink", "rock", "fairy" ],
  # [ 704, "Goomy", "dragon", "N/A" ],
  # [ 705, "Sliggoo", "dragon", "N/A" ],
  # [ 706, "Goodra", "dragon", "N/A" ],
  # [ 707, "Klefki", "steel", "fairy" ],
  # [ 708, "Phantump", "ghost", "grass" ],
  # [ 709, "Trevenant", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Average Size", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Small Size", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Large Size", "ghost", "grass" ],
  # [ 710, "Pumpkaboo Super Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Average Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Small Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Large Size", "ghost", "grass" ],
  # [ 711, "Gourgeist Super Size", "ghost", "grass" ],
  # [ 712, "Bergmite", "ice", "N/A" ],
  # [ 713, "Avalugg", "ice", "N/A" ],
  # [ 714, "Noibat", "flying", "dragon" ],
  # [ 715, "Noivern", "flying", "dragon" ],
  # [ 716, "Xerneas", "fairy", "N/A" ],
  # [ 717, "Yveltal", "dark", "flying" ],
  # [ 718, "Zygarde 50\% Form", "dragon", "ground" ],
  # [ 718, "Zygarde 10\% Form", "dragon", "ground" ],
  # [ 718, "Zygarde Complete Form", "dragon", "ground" ],
  # [ 719, "Diancie", "rock", "fairy" ],
  # [ 719, "Mega Diancie", "rock", "fairy" ],
  # [ 720, "Hoopa Confined", "psychic", "ghost" ],
  # [ 720, "Hoopa Unbound", "psychic", "dark" ],
  # [ 721, "Volcanion", "fire", "water" ],
  # [ 722, "Rowlet", "grass", "flying" ],
  # [ 723, "Dartrix", "grass", "flying" ],
  # [ 724, "Decidueye", "grass", "ghost" ],
  # [ 725, "Litten", "fire", "N/A" ],
  # [ 726, "Torracat", "fire", "N/A" ],
  # [ 727, "Incineroar", "fire", "dark" ],
  # [ 728, "Popplio", "water", "N/A" ],
  # [ 729, "Brionne", "water", "N/A" ],
  # [ 730, "Primarina", "water", "fairy" ],
  # [ 731, "Pikipek", "normal", "flying" ],
  # [ 732, "Trumbeak", "normal", "flying" ],
  # [ 733, "Toucannon", "normal", "flying" ],
  # [ 734, "Yungoos", "normal", "N/A" ],
  # [ 735, "Gumshoos", "normal", "N/A" ],
  # [ 736, "Grubbin", "bug", "N/A" ],
  # [ 737, "Charjabug", "bug", "electric" ],
  # [ 738, "Vikavolt", "bug", "electric" ],
  # [ 739, "Crabrawler", "fighting", "N/A" ],
  # [ 740, "Crabominable", "fighting", "ice" ],
  # [ 741, "Oricorio Baile Style", "fire", "flying" ],
  # [ 741, "Oricorio Pom-Pom Style", "electric", "flying" ],
  # [ 741, "Oricorio Pa'u Style", "psychic", "flying" ],
  # [ 741, "Oricorio Sensu Style", "ghost", "flying" ],
  # [ 742, "Cutiefly", "bug", "fairy" ],
  # [ 743, "Ribombee", "bug", "fairy" ],
  # [ 744, "Rockruff", "rock", "N/A" ],
  # [ 744, "Own Tempo Rockruff", "rock", "N/A" ],
  # [ 745, "Lycanroc Midday Form", "rock", "N/A" ],
  # [ 745, "Lycanroc Midnight Form", "rock", "N/A" ],
  # [ 745, "Lycanroc Dusk Form", "rock", "N/A" ],
  # [ 746, "Wishiwashi Solo Form", "water", "N/A" ],
  # [ 746, "Wishiwashi School Form", "water", "N/A" ],
  # [ 747, "Mareanie", "poison", "water" ],
  # [ 748, "Toxapex", "poison", "water" ],
  # [ 749, "Mudbray", "ground", "N/A" ],
  # [ 750, "Mudsdale", "ground", "N/A" ],
  # [ 751, "Dewpider", "water", "bug" ],
  # [ 752, "Araquanid", "water", "bug" ],
  # [ 753, "Fomantis", "grass", "N/A" ],
  # [ 754, "Lurantis", "grass", "N/A" ],
  # [ 755, "Morelull", "grass", "fairy" ],
  # [ 756, "Shiinotic", "grass", "fairy" ],
  # [ 757, "Salandit", "poison", "fire" ],
  # [ 758, "Salazzle", "poison", "fire" ],
  # [ 759, "Stufful", "normal", "fighting" ],
  # [ 760, "Bewear", "normal", "fighting" ],
  # [ 761, "Bounsweet", "grass", "N/A" ],
  # [ 762, "Steenee", "grass", "N/A" ],
  # [ 763, "Tsareena", "grass", "N/A" ],
  # [ 764, "Comfey", "fairy", "N/A" ],
  # [ 765, "Oranguru", "normal", "psychic" ],
  # [ 766, "Passimian", "fighting", "N/A" ],
  # [ 767, "Wimpod", "bug", "water" ],
  # [ 768, "Golisopod", "bug", "water" ],
  # [ 769, "Sandygast", "ghost", "ground" ],
  # [ 770, "Palossand", "ghost", "ground" ],
  # [ 771, "Pyukumuku", "water", "N/A" ],
  # [ 772, "Type: Null", "normal", "N/A" ],
  # [ 773, "Silvally", "normal", "N/A" ],
  # [ 774, "Minior Meteor Form", "rock", "flying" ],
  # [ 774, "Minior Core Form", "rock", "flying" ],
  # [ 775, "Komala", "normal", "N/A" ],
  # [ 776, "Turtonator", "fire", "dragon" ],
  # [ 777, "Togedemaru", "electric", "steel" ],
  # [ 778, "Mimikyu", "ghost", "fairy" ],
  # [ 779, "Bruxish", "water", "psychic" ],
  # [ 780, "Drampa", "normal", "dragon" ],
  # [ 781, "Dhelmise", "ghost", "grass" ],
  # [ 782, "Jangmo-o", "dragon", "N/A" ],
  # [ 783, "Hakamo-o", "dragon", "fighting" ],
  # [ 784, "Kommo-o", "dragon", "fighting" ],
  # [ 785, "Tapu Koko", "electric", "fairy" ],
  # [ 786, "Tapu Lele", "psychic", "fairy" ],
  # [ 787, "Tapu Bulu", "grass", "fairy" ],
  # [ 788, "Tapu Fini", "water", "fairy" ],
  # [ 789, "Cosmog", "psychic", "N/A" ],
  # [ 790, "Cosmoem", "psychic", "N/A" ],
  # [ 791, "Solgaleo", "psychic", "steel" ],
  # [ 792, "Lunala", "psychic", "ghost" ],
  # [ 793, "Nihilego", "rock", "poison" ],
  # [ 794, "Buzzwole", "bug", "fighting" ],
  # [ 795, "Pheromosa", "bug", "fighting" ],
  # [ 796, "Xurkitree", "electric", "N/A" ],
  # [ 797, "Celesteela", "steel", "flying" ],
  # [ 798, "Kartana", "grass", "steel" ],
  # [ 799, "Guzzlord", "dark", "dragon" ],
  # [ 800, "Necrozma", "psychic", "N/A" ],
  # [ 800, "Dusk Mane Necrozma", "psychic", "steel" ],
  # [ 800, "Dawn Wings Necrozma", "psychic", "ghost" ],
  # [ 800, "Ultra Necrozma", "psychic", "dragon" ],
  # [ 801, "Magearna", "steel", "fairy" ],
  # [ 802, "Marshadow", "fighting", "ghost" ],
  # [ 803, "Poipole", "poison", "N/A" ],
  # [ 804, "Naganadel", "poison", "dragon" ],
  # [ 805, "Stakataka", "rock", "steel" ],
  # [ 806, "Blacephalon", "fire", "ghost" ],
  # [ 807, "Zeraora", "electric", "N/A" ],
  # [ 808, "Meltan", "steel", "N/A" ],
  # [ 809, "Melmetal", "steel", "N/A" ]
]

pokemon_list.each do |pdNum, pmName, type1, type2|
  Pokemon.create( pokedex_number: pdNum, name: pmName, type1: type1, type2: type2)
end


#------------------------------------------------------------------------------------


move_list = [
  [ 1, "pound", "normal", "physical", "35", "40", "1", "I" ],
  [ 2, "karate chop", "fighting", "physical", "25", "50", "1", "I" ],
  [ 3, "double slap", "normal", "physical", "10", "15", "0.85", "I" ],
  [ 4, "comet punch", "normal", "physical", "15", "18", "0.85", "I" ],
  [ 5, "mega punch", "normal", "physical", "20", "80", "0.85", "I" ],
  [ 6, "pay day", "normal", "physical", "20", "40", "1", "I" ],
  [ 7, "fire punch", "fire", "physical", "15", "75", "1", "I" ],
  [ 8, "ice punch", "ice", "physical", "15", "75", "1", "I" ],
  [ 9, "thunder punch", "electric", "physical", "15", "75", "1", "I" ],
  [ 10, "scratch", "normal", "physical", "35", "40", "1", "I" ],
  [ 11, "vice grip", "normal", "physical", "30", "55", "1", "I" ],
  [ 12, "guillotine", "normal", "physical", "5", "N/A", "N/A", "I" ],
  [ 13, "razor wind", "normal", "special", "10", "80", "1", "I" ],
  [ 14, "swords dance", "normal", "status", "20", "N/A", "N/A", "I" ],
  [ 15, "cut", "normal", "physical", "30", "50", "0.95", "I" ],
  [ 16, "gust", "flying", "special", "35", "40", "1", "I" ],
  [ 17, "wing attack", "flying", "physical", "35", "60", "1", "I" ],
  [ 18, "whirlwind", "normal", "status", "20", "N/A", "N/A", "I" ],
  [ 19, "fly", "flying", "physical", "15", "90", "0.95", "I" ],
  [ 20, "bind", "normal", "physical", "20", "15", "0.85", "I" ],
  [ 21, "slam", "normal", "physical", "20", "80", "0.75", "I" ],
  [ 22, "vine whip", "grass", "physical", "25", "45", "1", "I" ],
  [ 23, "stomp", "normal", "physical", "20", "65", "1", "I" ],
  [ 24, "double kick", "fighting", "physical", "30", "30", "1", "I" ],
  [ 25, "mega kick", "normal", "physical", "5", "120", "0.75", "I" ],
  [ 26, "jump kick", "fighting", "physical", "10", "100", "0.95", "I" ],
  [ 27, "rolling kick", "fighting", "physical", "15", "60", "0.85", "I" ],
  [ 28, "sand attack", "ground", "status", "15", "N/A", "1", "I" ],
  [ 29, "headbutt", "normal", "physical", "15", "70", "1", "I" ],
  [ 30, "horn attack", "normal", "physical", "25", "65", "1", "I" ],
  [ 31, "fury attack", "normal", "physical", "20", "15", "0.85", "I" ],
  [ 32, "horn drill", "normal", "physical", "5", "N/A", "N/A", "I" ],
  [ 33, "tackle", "normal", "physical", "35", "40", "1", "I" ],
  [ 34, "body slam", "normal", "physical", "15", "85", "1", "I" ],
  [ 35, "wrap", "normal", "physical", "20", "15", "0.9", "I" ],
  [ 36, "take down", "normal", "physical", "20", "90", "0.85", "I" ],
  [ 37, "thrash", "normal", "physical", "10", "120", "1", "I" ],
  [ 38, "double-edge", "normal", "physical", "15", "120", "1", "I" ],
  [ 39, "tail whip", "normal", "status", "30", "N/A", "1", "I" ],
  [ 40, "poison sting", "poison", "physical", "35", "15", "1", "I" ],
  [ 41, "twineedle", "bug", "physical", "20", "25", "1", "I" ],
  [ 42, "pin missile", "bug", "physical", "20", "25", "0.95", "I" ],
  [ 43, "leer", "normal", "status", "30", "N/A", "1", "I" ],
  [ 44, "bite", "dark", "physical", "25", "60", "1", "I" ],
  [ 45, "growl", "normal", "status", "40", "N/A", "1", "I" ],
  [ 46, "roar", "normal", "status", "20", "N/A", "N/A", "I" ],
  [ 47, "sing", "normal", "status", "15", "N/A", "0.55", "I" ],
  [ 48, "supersonic", "normal", "status", "20", "N/A", "0.55", "I" ],
  [ 49, "sonic boom", "normal", "special", "20", "", "0.9", "I" ],
  [ 50, "disable", "normal", "status", "20", "N/A", "1", "I" ],
  [ 51, "acid", "poison", "special", "30", "40", "1", "I" ],
  [ 52, "ember", "fire", "special", "25", "40", "1", "I" ],
  [ 53, "flamethrower", "fire", "special", "15", "90", "1", "I" ],
  [ 54, "mist", "ice", "status", "30", "N/A", "N/A", "I" ],
  [ 55, "water gun", "water", "special", "25", "40", "1", "I" ],
  [ 56, "hydro pump", "water", "special", "5", "110", "0.8", "I" ],
  [ 57, "surf", "water", "special", "15", "90", "1", "I" ],
  [ 58, "ice beam", "ice", "special", "10", "90", "1", "I" ],
  [ 59, "blizzard", "ice", "special", "5", "110", "0.7", "I" ],
  [ 60, "psybeam", "psychic", "special", "20", "65", "1", "I" ],
  [ 61, "bubble beam", "water", "special", "20", "65", "1", "I" ],
  [ 62, "aurora beam", "ice", "special", "20", "65", "1", "I" ],
  [ 63, "hyper beam", "normal", "special", "5", "150", "0.9", "I" ],
  [ 64, "peck", "flying", "physical", "35", "35", "1", "I" ],
  [ 65, "drill peck", "flying", "physical", "20", "80", "1", "I" ],
  [ 66, "submission", "fighting", "physical", "20", "80", "0.8", "I" ],
  [ 67, "low kick", "fighting", "physical", "20", "N/A", "1", "I" ],
  [ 68, "counter", "fighting", "physical", "20", "N/A", "1", "I" ],
  [ 69, "seismic toss", "fighting", "physical", "20", "N/A", "1", "I" ],
  [ 70, "strength", "normal", "physical", "15", "80", "1", "I" ],
  [ 71, "absorb", "grass", "special", "15", "40", "1", "I" ],
  [ 72, "mega drain", "grass", "special", "10", "75", "1", "I" ],
  [ 73, "leech seed", "grass", "status", "10", "N/A", "0.9", "I" ],
  [ 74, "growth", "normal", "status", "20", "N/A", "N/A", "I" ],
  [ 75, "razor leaf", "grass", "physical", "25", "55", "0.95", "I" ],
  [ 76, "solar beam", "grass", "special", "10", "200", "1", "I" ],
  [ 77, "poison powder", "poison", "status", "35", "N/A", "0.75", "I" ],
  [ 78, "stun spore", "grass", "status", "30", "N/A", "0.75", "I" ],
  [ 79, "sleep powder", "grass", "status", "15", "N/A", "0.75", "I" ],
  [ 80, "petal dance", "grass", "special", "10", "120", "1", "I" ],
  [ 81, "string shot", "bug", "status", "40", "N/A", "0.95", "I" ],
  [ 82, "dragon rage", "dragon", "special", "10", "", "1", "I" ],
  [ 83, "fire spin", "fire", "special", "15", "35", "0.85", "I" ],
  [ 84, "thunder shock", "electric", "special", "30", "40", "1", "I" ],
  [ 85, "thunderbolt", "electric", "special", "15", "90", "1", "I" ],
  [ 86, "thunder wave", "electric", "status", "20", "N/A", "0.9", "I" ],
  [ 87, "thunder", "electric", "special", "10", "110", "0.7", "I" ],
  [ 88, "rock throw", "rock", "physical", "15", "50", "0.9", "I" ],
  [ 89, "earthquake", "ground", "physical", "10", "100", "1", "I" ],
  [ 90, "fissure", "ground", "physical", "5", "N/A", "N/A", "I" ],
  [ 91, "dig", "ground", "physical", "10", "80", "1", "I" ],
  [ 92, "toxic", "poison", "status", "10", "N/A", "0.9", "I" ],
  [ 93, "confusion", "psychic", "special", "25", "50", "1", "I" ],
  [ 94, "psychic", "psychic", "special", "10", "90", "1", "I" ],
  [ 95, "hypnosis", "psychic", "status", "20", "N/A", "0.6", "I" ],
  [ 96, "meditate", "psychic", "status", "40", "N/A", "N/A", "I" ],
  [ 97, "agility", "psychic", "status", "30", "N/A", "N/A", "I" ],
  [ 98, "quick attack", "normal", "physical", "30", "40", "1", "I" ],
  [ 99, "rage", "normal", "physical", "20", "20", "1", "I" ],
  [ 100, "teleport", "psychic", "status", "20", "N/A", "N/A", "I" ],
  [ 101, "night shade", "ghost", "special", "15", "N/A", "1", "I" ],
  [ 102, "mimic", "normal", "status", "10", "N/A", "N/A", "I" ],
  [ 103, "screech", "normal", "status", "40", "N/A", "0.85", "I" ],
  [ 104, "double team", "normal", "status", "15", "N/A", "N/A", "I" ],
  [ 105, "recover", "normal", "status", "10", "N/A", "N/A", "I" ],
  [ 106, "harden", "normal", "status", "30", "N/A", "N/A", "I" ],
  [ 107, "minimize", "normal", "status", "10", "N/A", "N/A", "I" ],
  [ 108, "smokescreen", "normal", "status", "20", "N/A", "1", "I" ],
  [ 109, "confuse ray", "ghost", "status", "10", "N/A", "1", "I" ],
  [ 110, "withdraw", "water", "status", "40", "N/A", "N/A", "I" ],
  [ 111, "defense curl", "normal", "status", "40", "N/A", "N/A", "I" ],
  [ 112, "barrier", "psychic", "status", "20", "N/A", "N/A", "I" ],
  [ 113, "light screen", "psychic", "status", "30", "N/A", "N/A", "I" ],
  [ 114, "haze", "ice", "status", "30", "N/A", "N/A", "I" ],
  [ 115, "reflect", "psychic", "status", "20", "N/A", "N/A", "I" ],
  [ 116, "focus energy", "normal", "status", "30", "N/A", "N/A", "I" ],
  [ 117, "bide", "normal", "physical", "10", "N/A", "N/A", "I" ],
  [ 118, "metronome", "normal", "status", "10", "N/A", "N/A", "I" ],
  [ 119, "mirror move", "flying", "status", "20", "N/A", "N/A", "I" ],
  [ 120, "self-destruct", "normal", "physical", "5", "200", "1", "I" ],
  [ 121, "egg bomb", "normal", "physical", "10", "100", "0.75", "I" ],
  [ 122, "lick", "ghost", "physical", "30", "30", "1", "I" ],
  [ 123, "smog", "poison", "special", "20", "30", "0.7", "I" ],
  [ 124, "sludge", "poison", "special", "20", "65", "1", "I" ],
  [ 125, "bone club", "ground", "physical", "20", "65", "0.85", "I" ],
  [ 126, "fire blast", "fire", "special", "5", "110", "0.85", "I" ],
  [ 127, "waterfall", "water", "physical", "15", "80", "1", "I" ],
  [ 128, "clamp", "water", "physical", "15", "35", "0.85", "I" ],
  [ 129, "swift", "normal", "special", "20", "60", "N/A", "I" ],
  [ 130, "skull bash", "normal", "physical", "10", "130", "1", "I" ],
  [ 131, "spike cannon", "normal", "physical", "15", "20", "1", "I" ],
  [ 132, "constrict", "normal", "physical", "35", "10", "1", "I" ],
  [ 133, "amnesia", "psychic", "status", "20", "N/A", "N/A", "I" ],
  [ 134, "kinesis", "psychic", "status", "15", "N/A", "0.8", "I" ],
  [ 135, "soft-boiled", "normal", "status", "10", "N/A", "N/A", "I" ],
  [ 136, "high jump kick", "fighting", "physical", "10", "130", "0.9", "I" ],
  [ 137, "glare", "normal", "status", "30", "N/A", "1", "I" ],
  [ 138, "dream eater", "psychic", "special", "15", "100", "1", "I" ],
  [ 139, "poison gas", "poison", "status", "40", "N/A", "0.9", "I" ],
  [ 140, "barrage", "normal", "physical", "20", "15", "0.85", "I" ],
  [ 141, "leech life", "bug", "physical", "10", "80", "1", "I" ],
  [ 142, "lovely kiss", "normal", "status", "10", "N/A", "0.75", "I" ],
  [ 143, "sky attack", "flying", "physical", "5", "200", "0.9", "I" ],
  [ 144, "transform", "normal", "status", "10", "N/A", "N/A", "I" ],
  [ 145, "bubble", "water", "special", "30", "40", "1", "I" ],
  [ 146, "dizzy punch", "normal", "physical", "10", "70", "1", "I" ],
  [ 147, "spore", "grass", "status", "15", "N/A", "1", "I" ],
  [ 148, "flash", "normal", "status", "20", "N/A", "1", "I" ],
  [ 149, "psywave", "psychic", "special", "15", "N/A", "1", "I" ],
  [ 150, "splash", "normal", "status", "40", "N/A", "N/A", "I" ],
  [ 151, "acid armor", "poison", "status", "20", "N/A", "N/A", "I" ],
  [ 152, "crabhammer", "water", "physical", "10", "100", "0.9", "I" ],
  [ 153, "explosion", "normal", "physical", "5", "250", "1", "I" ],
  [ 154, "fury swipes", "normal", "physical", "15", "18", "0.8", "I" ],
  [ 155, "bonemerang", "ground", "physical", "10", "50", "0.9", "I" ],
  [ 156, "rest", "psychic", "status", "10", "N/A", "N/A", "I" ],
  [ 157, "rock slide", "rock", "physical", "10", "75", "0.9", "I" ],
  [ 158, "hyper fang", "normal", "physical", "15", "80", "0.9", "I" ],
  [ 159, "sharpen", "normal", "status", "30", "N/A", "N/A", "I" ],
  [ 160, "conversion", "normal", "status", "30", "N/A", "N/A", "I" ],
  [ 161, "tri attack", "normal", "special", "10", "80", "1", "I" ],
  [ 162, "super fang", "normal", "physical", "10", "N/A", "0.9", "I" ],
  [ 163, "slash", "normal", "physical", "20", "70", "1", "I" ],
  [ 164, "substitute", "normal", "status", "10", "N/A", "N/A", "I" ],
  [ 165, "struggle", "normal", "physical", "1", "50", "N/A", "I" ],
  [ 166, "sketch", "normal", "status", "1", "N/A", "N/A", "II" ],
  [ 167, "triple kick", "fighting", "physical", "10", "10", "0.9", "II" ],
  [ 168, "thief", "dark", "physical", "25", "60", "1", "II" ],
  [ 169, "spider web", "bug", "status", "10", "N/A", "N/A", "II" ],
  [ 170, "mind reader", "normal", "status", "5", "N/A", "N/A", "II" ],
  [ 171, "nightmare", "ghost", "status", "15", "N/A", "1", "II" ],
  [ 172, "flame wheel", "fire", "physical", "25", "60", "1", "II" ],
  [ 173, "snore", "normal", "special", "15", "50", "1", "II" ],
  [ 174, "curse", "ghost", "status", "10", "N/A", "N/A", "II" ],
  [ 175, "flail", "normal", "physical", "15", "N/A", "1", "II" ],
  [ 176, "conversion 2", "normal", "status", "30", "N/A", "N/A", "II" ],
  [ 177, "aeroblast", "flying", "special", "5", "100", "0.95", "II" ],
  [ 178, "cotton spore", "grass", "status", "40", "N/A", "1", "II" ],
  [ 179, "reversal", "fighting", "physical", "15", "N/A", "1", "II" ],
  [ 180, "spite", "ghost", "status", "10", "N/A", "1", "II" ],
  [ 181, "powder snow", "ice", "special", "25", "40", "1", "II" ],
  [ 182, "protect", "normal", "status", "10", "N/A", "N/A", "II" ],
  [ 183, "mach punch", "fighting", "physical", "30", "40", "1", "II" ],
  [ 184, "scary face", "normal", "status", "10", "N/A", "1", "II" ],
  [ 185, "feint attack", "dark", "physical", "20", "60", "N/A", "II" ],
  [ 186, "sweet kiss", "fairy", "status", "10", "N/A", "0.75", "II" ],
  [ 187, "belly drum", "normal", "status", "10", "N/A", "N/A", "II" ],
  [ 188, "sludge bomb", "poison", "special", "10", "90", "1", "II" ],
  [ 189, "mud-slap", "ground", "special", "10", "20", "1", "II" ],
  [ 190, "octazooka", "water", "special", "10", "65", "0.85", "II" ],
  [ 191, "spikes", "ground", "status", "20", "N/A", "N/A", "II" ],
  [ 192, "zap cannon", "electric", "special", "5", "120", "0.5", "II" ],
  [ 193, "foresight", "normal", "status", "40", "N/A", "N/A", "II" ],
  [ 194, "destiny bond", "ghost", "status", "5", "N/A", "N/A", "II" ],
  [ 195, "perish song", "normal", "status", "5", "N/A", "N/A", "II" ],
  [ 196, "icy wind", "ice", "special", "15", "55", "0.95", "II" ],
  [ 197, "detect", "fighting", "status", "5", "N/A", "N/A", "II" ],
  [ 198, "bone rush", "ground", "physical", "10", "25", "0.9", "II" ],
  [ 199, "lock-on", "normal", "status", "5", "N/A", "N/A", "II" ],
  [ 200, "outrage", "dragon", "physical", "10", "120", "1", "II" ],
  [ 201, "sandstorm", "rock", "status", "10", "N/A", "N/A", "II" ],
  [ 202, "giga drain", "grass", "special", "10", "75", "1", "II" ],
  [ 203, "endure", "normal", "status", "10", "N/A", "N/A", "II" ],
  [ 204, "charm", "fairy", "status", "20", "N/A", "1", "II" ],
  [ 205, "rollout", "rock", "physical", "20", "30", "0.9", "II" ],
  [ 206, "false swipe", "normal", "physical", "40", "40", "1", "II" ],
  [ 207, "swagger", "normal", "status", "15", "N/A", "0.85", "II" ],
  [ 208, "milk drink", "normal", "status", "10", "N/A", "N/A", "II" ],
  [ 209, "spark", "electric", "physical", "20", "65", "1", "II" ],
  [ 210, "fury cutter", "bug", "physical", "20", "40", "0.95", "II" ],
  [ 211, "steel wing", "steel", "physical", "25", "70", "0.9", "II" ],
  [ 212, "mean look", "normal", "status", "5", "N/A", "N/A", "II" ],
  [ 213, "attract", "normal", "status", "15", "N/A", "1", "II" ],
  [ 214, "sleep talk", "normal", "status", "10", "N/A", "N/A", "II" ],
  [ 215, "heal bell", "normal", "status", "5", "N/A", "N/A", "II" ],
  [ 216, "return", "normal", "physical", "20", "N/A", "1", "II" ],
  [ 217, "present", "normal", "physical", "15", "N/A", "0.9", "II" ],
  [ 218, "frustration", "normal", "physical", "20", "N/A", "1", "II" ],
  [ 219, "safeguard", "normal", "status", "25", "N/A", "N/A", "II" ],
  [ 220, "pain split", "normal", "status", "20", "N/A", "N/A", "II" ],
  [ 221, "sacred fire", "fire", "physical", "5", "100", "0.95", "II" ],
  [ 222, "magnitude", "ground", "physical", "30", "N/A", "1", "II" ],
  [ 223, "dynamic punch", "fighting", "physical", "5", "100", "0.5", "II" ],
  [ 224, "megahorn", "bug", "physical", "10", "120", "0.85", "II" ],
  [ 225, "dragon breath", "dragon", "special", "20", "60", "1", "II" ],
  [ 226, "baton pass", "normal", "status", "40", "N/A", "N/A", "II" ],
  [ 227, "encore", "normal", "status", "5", "N/A", "1", "II" ],
  [ 228, "pursuit", "dark", "physical", "20", "40", "1", "II" ],
  [ 229, "rapid spin", "normal", "physical", "40", "20", "1", "II" ],
  [ 230, "sweet scent", "normal", "status", "20", "N/A", "1", "II" ],
  [ 231, "iron tail", "steel", "physical", "15", "100", "0.75", "II" ],
  [ 232, "metal claw", "steel", "physical", "35", "50", "0.95", "II" ],
  [ 233, "vital throw", "fighting", "physical", "10", "70", "N/A", "II" ],
  [ 234, "morning sun", "normal", "status", "5", "N/A", "N/A", "II" ],
  [ 235, "synthesis", "grass", "status", "5", "N/A", "N/A", "II" ],
  [ 236, "moonlight", "fairy", "status", "5", "N/A", "N/A", "II" ],
  [ 237, "hidden power", "normal", "special", "15", "60", "1", "II" ],
  [ 238, "cross chop", "fighting", "physical", "5", "100", "0.8", "II" ],
  [ 239, "twister", "dragon", "special", "20", "40", "1", "II" ],
  [ 240, "rain dance", "water", "status", "5", "N/A", "N/A", "II" ],
  [ 241, "sunny day", "fire", "status", "5", "N/A", "N/A", "II" ],
  [ 242, "crunch", "dark", "physical", "15", "80", "1", "II" ],
  [ 243, "mirror coat", "psychic", "special", "20", "N/A", "1", "II" ],
  [ 244, "psych up", "normal", "status", "10", "N/A", "N/A", "II" ],
  [ 245, "extreme speed", "normal", "physical", "5", "80", "1", "II" ],
  [ 246, "ancient power", "rock", "special", "5", "60", "1", "II" ],
  [ 247, "shadow ball", "ghost", "special", "15", "80", "1", "II" ],
  [ 248, "future sight", "psychic", "special", "10", "120", "1", "II" ],
  [ 249, "rock smash", "fighting", "physical", "15", "40", "1", "II" ],
  [ 250, "whirlpool", "water", "special", "15", "35", "0.85", "II" ],
  [ 251, "beat up", "dark", "physical", "10", "N/A", "1", "II" ],
  [ 252, "fake out", "normal", "physical", "10", "40", "1", "III" ],
  [ 253, "uproar", "normal", "special", "10", "90", "1", "III" ],
  [ 254, "stockpile", "normal", "status", "20", "N/A", "N/A", "III" ],
  [ 255, "spit up", "normal", "special", "10", "N/A", "1", "III" ],
  [ 256, "swallow", "normal", "status", "10", "N/A", "N/A", "III" ],
  [ 257, "heat wave", "fire", "special", "10", "95", "0.9", "III" ],
  [ 258, "hail", "ice", "status", "10", "N/A", "N/A", "III" ],
  [ 259, "torment", "dark", "status", "15", "N/A", "1", "III" ],
  [ 260, "flatter", "dark", "status", "15", "N/A", "1", "III" ],
  [ 261, "will-o-wisp", "fire", "status", "15", "N/A", "0.85", "III" ],
  [ 262, "memento", "dark", "status", "10", "N/A", "1", "III" ],
  [ 263, "facade", "normal", "physical", "20", "70", "1", "III" ],
  [ 264, "focus punch", "fighting", "physical", "20", "150", "1", "III" ],
  [ 265, "smelling salts", "normal", "physical", "10", "70", "1", "III" ],
  [ 266, "follow me", "normal", "status", "20", "N/A", "N/A", "III" ],
  [ 267, "nature power", "normal", "status", "20", "N/A", "N/A", "III" ],
  [ 268, "charge", "electric", "status", "20", "N/A", "N/A", "III" ],
  [ 269, "taunt", "dark", "status", "20", "N/A", "1", "III" ],
  [ 270, "helping hand", "normal", "status", "20", "N/A", "N/A", "III" ],
  [ 271, "trick", "psychic", "status", "10", "N/A", "1", "III" ],
  [ 272, "role play", "psychic", "status", "10", "N/A", "N/A", "III" ],
  [ 273, "wish", "normal", "status", "10", "N/A", "N/A", "III" ],
  [ 274, "assist", "normal", "status", "20", "N/A", "N/A", "III" ],
  [ 275, "ingrain", "grass", "status", "20", "N/A", "N/A", "III" ],
  [ 276, "superpower", "fighting", "physical", "5", "120", "1", "III" ],
  [ 277, "magic coat", "psychic", "status", "15", "N/A", "N/A", "III" ],
  [ 278, "recycle", "normal", "status", "10", "N/A", "N/A", "III" ],
  [ 279, "revenge", "fighting", "physical", "10", "60", "1", "III" ],
  [ 280, "brick break", "fighting", "physical", "15", "75", "1", "III" ],
  [ 281, "yawn", "normal", "status", "10", "N/A", "N/A", "III" ],
  [ 282, "knock off", "dark", "physical", "20", "65", "1", "III" ],
  [ 283, "endeavor", "normal", "physical", "5", "N/A", "1", "III" ],
  [ 284, "eruption", "fire", "special", "5", "150", "1", "III" ],
  [ 285, "skill swap", "psychic", "status", "10", "N/A", "N/A", "III" ],
  [ 286, "imprison", "psychic", "status", "10", "N/A", "N/A", "III" ],
  [ 287, "refresh", "normal", "status", "20", "N/A", "N/A", "III" ],
  [ 288, "grudge", "ghost", "status", "5", "N/A", "N/A", "III" ],
  [ 289, "snatch", "dark", "status", "10", "N/A", "N/A", "III" ],
  [ 290, "secret power", "normal", "physical", "20", "70", "1", "III" ],
  [ 291, "dive", "water", "physical", "10", "80", "1", "III" ],
  [ 292, "arm thrust", "fighting", "physical", "20", "15", "1", "III" ],
  [ 293, "camouflage", "normal", "status", "20", "N/A", "N/A", "III" ],
  [ 294, "tail glow", "bug", "status", "20", "N/A", "N/A", "III" ],
  [ 295, "luster purge", "psychic", "special", "5", "70", "1", "III" ],
  [ 296, "mist ball", "psychic", "special", "5", "70", "1", "III" ],
  [ 297, "feather dance", "flying", "status", "15", "N/A", "1", "III" ],
  [ 298, "teeter dance", "normal", "status", "20", "N/A", "1", "III" ],
  [ 299, "blaze kick", "fire", "physical", "10", "85", "0.9", "III" ],
  [ 300, "mud sport", "ground", "status", "15", "N/A", "N/A", "III" ],
  [ 301, "ice ball", "ice", "physical", "20", "30", "0.9", "III" ],
  [ 302, "needle arm", "grass", "physical", "15", "60", "1", "III" ],
  [ 303, "slack off", "normal", "status", "10", "N/A", "N/A", "III" ],
  [ 304, "hyper voice", "normal", "special", "10", "90", "1", "III" ],
  [ 305, "poison fang", "poison", "physical", "15", "50", "1", "III" ],
  [ 306, "crush claw", "normal", "physical", "10", "75", "0.95", "III" ],
  [ 307, "blast burn", "fire", "special", "5", "150", "0.9", "III" ],
  [ 308, "hydro cannon", "water", "special", "5", "150", "0.9", "III" ],
  [ 309, "meteor mash", "steel", "physical", "10", "90", "0.9", "III" ],
  [ 310, "astonish", "ghost", "physical", "15", "30", "1", "III" ],
  [ 311, "weather ball", "normal", "special", "10", "50", "1", "III" ],
  [ 312, "aromatherapy", "grass", "status", "5", "N/A", "N/A", "III" ],
  [ 313, "fake tears", "dark", "status", "20", "N/A", "1", "III" ],
  [ 314, "air cutter", "flying", "special", "25", "60", "0.95", "III" ],
  [ 315, "overheat", "fire", "special", "5", "130", "0.9", "III" ],
  [ 316, "odor sleuth", "normal", "status", "40", "N/A", "N/A", "III" ],
  [ 317, "rock tomb", "rock", "physical", "15", "60", "0.95", "III" ],
  [ 318, "silver wind", "bug", "special", "5", "60", "1", "III" ],
  [ 319, "metal sound", "steel", "status", "40", "N/A", "0.85", "III" ],
  [ 320, "grass whistle", "grass", "status", "15", "N/A", "0.55", "III" ],
  [ 321, "tickle", "normal", "status", "20", "N/A", "1", "III" ],
  [ 322, "cosmic power", "psychic", "status", "20", "N/A", "N/A", "III" ],
  [ 323, "water spout", "water", "special", "5", "150", "1", "III" ],
  [ 324, "signal beam", "bug", "special", "15", "75", "1", "III" ],
  [ 325, "shadow punch", "ghost", "physical", "20", "60", "N/A", "III" ],
  [ 326, "extrasensory", "psychic", "special", "20", "80", "1", "III" ],
  [ 327, "sky uppercut", "fighting", "physical", "15", "85", "0.9", "III" ],
  [ 328, "sand tomb", "ground", "physical", "15", "35", "0.85", "III" ],
  [ 329, "sheer cold", "ice", "special", "5", "N/A", "N/A", "III" ],
  [ 330, "muddy water", "water", "special", "10", "90", "0.85", "III" ],
  [ 331, "bullet seed", "grass", "physical", "30", "25", "1", "III" ],
  [ 332, "aerial ace", "flying", "physical", "20", "60", "N/A", "III" ],
  [ 333, "icicle spear", "ice", "physical", "30", "25", "1", "III" ],
  [ 334, "iron defense", "steel", "status", "15", "N/A", "N/A", "III" ],
  [ 335, "block", "normal", "status", "5", "N/A", "N/A", "III" ],
  [ 336, "howl", "normal", "status", "40", "N/A", "N/A", "III" ],
  [ 337, "dragon claw", "dragon", "physical", "15", "80", "1", "III" ],
  [ 338, "frenzy plant", "grass", "special", "5", "150", "0.9", "III" ],
  [ 339, "bulk up", "fighting", "status", "20", "N/A", "N/A", "III" ],
  [ 340, "bounce", "flying", "physical", "5", "85", "0.85", "III" ],
  [ 341, "mud shot", "ground", "special", "15", "55", "0.95", "III" ],
  [ 342, "poison tail", "poison", "physical", "25", "50", "1", "III" ],
  [ 343, "covet", "normal", "physical", "25", "60", "1", "III" ],
  [ 344, "volt tackle", "electric", "physical", "15", "120", "1", "III" ],
  [ 345, "magical leaf", "grass", "special", "20", "60", "N/A", "III" ],
  [ 346, "water sport", "water", "status", "15", "N/A", "N/A", "III" ],
  [ 347, "calm mind", "psychic", "status", "20", "N/A", "N/A", "III" ],
  [ 348, "leaf blade", "grass", "physical", "15", "90", "1", "III" ],
  [ 349, "dragon dance", "dragon", "status", "20", "N/A", "N/A", "III" ],
  [ 350, "rock blast", "rock", "physical", "10", "25", "0.9", "III" ],
  [ 351, "shock wave", "electric", "special", "20", "60", "N/A", "III" ],
  [ 352, "water pulse", "water", "special", "20", "60", "1", "III" ],
  [ 353, "doom desire", "steel", "special", "5", "140", "1", "III" ],
  [ 354, "psycho boost", "psychic", "special", "5", "140", "0.9", "III" ],
  [ 355, "roost", "flying", "status", "10", "N/A", "N/A", "IV" ],
  [ 356, "gravity", "psychic", "status", "5", "N/A", "N/A", "IV" ],
  [ 357, "miracle eye", "psychic", "status", "40", "N/A", "N/A", "IV" ],
  [ 358, "wake-up slap", "fighting", "physical", "10", "70", "1", "IV" ],
  [ 359, "hammer arm", "fighting", "physical", "10", "100", "0.9", "IV" ],
  [ 360, "gyro ball", "steel", "physical", "5", "N/A", "1", "IV" ],
  [ 361, "healing wish", "psychic", "status", "10", "N/A", "N/A", "IV" ],
  [ 362, "brine", "water", "special", "10", "65", "1", "IV" ],
  [ 363, "natural gift", "normal", "physical", "15", "N/A", "1", "IV" ],
  [ 364, "feint", "normal", "physical", "10", "30", "1", "IV" ],
  [ 365, "pluck", "flying", "physical", "20", "60", "1", "IV" ],
  [ 366, "tailwind", "flying", "status", "15", "N/A", "N/A", "IV" ],
  [ 367, "acupressure", "normal", "status", "30", "N/A", "N/A", "IV" ],
  [ 368, "metal burst", "steel", "physical", "10", "N/A", "1", "IV" ],
  [ 369, "u-turn", "bug", "physical", "20", "70", "1", "IV" ],
  [ 370, "close combat", "fighting", "physical", "5", "120", "1", "IV" ],
  [ 371, "payback", "dark", "physical", "10", "50", "1", "IV" ],
  [ 372, "assurance", "dark", "physical", "10", "60", "1", "IV" ],
  [ 373, "embargo", "dark", "status", "15", "N/A", "1", "IV" ],
  [ 374, "fling", "dark", "physical", "10", "N/A", "1", "IV" ],
  [ 375, "psycho shift", "psychic", "status", "10", "N/A", "1", "IV" ],
  [ 376, "trump card", "normal", "special", "5", "N/A", "N/A", "IV" ],
  [ 377, "heal block", "psychic", "status", "15", "N/A", "1", "IV" ],
  [ 378, "wring out", "normal", "special", "5", "N/A", "1", "IV" ],
  [ 379, "power trick", "psychic", "status", "10", "N/A", "N/A", "IV" ],
  [ 380, "gastro acid", "poison", "status", "10", "N/A", "1", "IV" ],
  [ 381, "lucky chant", "normal", "status", "30", "N/A", "N/A", "IV" ],
  [ 382, "me first", "normal", "status", "20", "N/A", "N/A", "IV" ],
  [ 383, "copycat", "normal", "status", "20", "N/A", "N/A", "IV" ],
  [ 384, "power swap", "psychic", "status", "10", "N/A", "N/A", "IV" ],
  [ 385, "guard swap", "psychic", "status", "10", "N/A", "N/A", "IV" ],
  [ 386, "punishment", "dark", "physical", "5", "N/A", "1", "IV" ],
  [ 387, "last resort", "normal", "physical", "5", "140", "1", "IV" ],
  [ 388, "worry seed", "grass", "status", "10", "N/A", "1", "IV" ],
  [ 389, "sucker punch", "dark", "physical", "5", "70", "1", "IV" ],
  [ 390, "toxic spikes", "poison", "status", "20", "N/A", "N/A", "IV" ],
  [ 391, "heart swap", "psychic", "status", "10", "N/A", "N/A", "IV" ],
  [ 392, "aqua ring", "water", "status", "20", "N/A", "N/A", "IV" ],
  [ 393, "magnet rise", "electric", "status", "10", "N/A", "N/A", "IV" ],
  [ 394, "flare blitz", "fire", "physical", "15", "120", "1", "IV" ],
  [ 395, "force palm", "fighting", "physical", "10", "60", "1", "IV" ],
  [ 396, "aura sphere", "fighting", "special", "20", "80", "N/A", "IV" ],
  [ 397, "rock polish", "rock", "status", "20", "N/A", "N/A", "IV" ],
  [ 398, "poison jab", "poison", "physical", "20", "80", "1", "IV" ],
  [ 399, "dark pulse", "dark", "special", "15", "80", "1", "IV" ],
  [ 400, "night slash", "dark", "physical", "15", "70", "1", "IV" ],
  [ 401, "aqua tail", "water", "physical", "10", "90", "0.9", "IV" ],
  [ 402, "seed bomb", "grass", "physical", "15", "80", "1", "IV" ],
  [ 403, "air slash", "flying", "special", "15", "75", "0.95", "IV" ],
  [ 404, "x-scissor", "bug", "physical", "15", "80", "1", "IV" ],
  [ 405, "bug buzz", "bug", "special", "10", "90", "1", "IV" ],
  [ 406, "dragon pulse", "dragon", "special", "10", "85", "1", "IV" ],
  [ 407, "dragon rush", "dragon", "physical", "10", "100", "0.75", "IV" ],
  [ 408, "power gem", "rock", "special", "20", "80", "1", "IV" ],
  [ 409, "drain punch", "fighting", "physical", "10", "75", "1", "IV" ],
  [ 410, "vacuum wave", "fighting", "special", "30", "40", "1", "IV" ],
  [ 411, "focus blast", "fighting", "special", "5", "120", "0.7", "IV" ],
  [ 412, "energy ball", "grass", "special", "10", "90", "1", "IV" ],
  [ 413, "brave bird", "flying", "physical", "15", "120", "1", "IV" ],
  [ 414, "earth power", "ground", "special", "10", "90", "1", "IV" ],
  [ 415, "switcheroo", "dark", "status", "10", "N/A", "1", "IV" ],
  [ 416, "giga impact", "normal", "physical", "5", "150", "0.9", "IV" ],
  [ 417, "nasty plot", "dark", "status", "20", "N/A", "N/A", "IV" ],
  [ 418, "bullet punch", "steel", "physical", "30", "40", "1", "IV" ],
  [ 419, "avalanche", "ice", "physical", "10", "60", "1", "IV" ],
  [ 420, "ice shard", "ice", "physical", "30", "40", "1", "IV" ],
  [ 421, "shadow claw", "ghost", "physical", "15", "70", "1", "IV" ],
  [ 422, "thunder fang", "electric", "physical", "15", "65", "0.95", "IV" ],
  [ 423, "ice fang", "ice", "physical", "15", "65", "0.95", "IV" ],
  [ 424, "fire fang", "fire", "physical", "15", "65", "0.95", "IV" ],
  [ 425, "shadow sneak", "ghost", "physical", "30", "40", "1", "IV" ],
  [ 426, "mud bomb", "ground", "special", "10", "65", "0.85", "IV" ],
  [ 427, "psycho cut", "psychic", "physical", "20", "70", "1", "IV" ],
  [ 428, "zen headbutt", "psychic", "physical", "15", "80", "0.9", "IV" ],
  [ 429, "mirror shot", "steel", "special", "10", "65", "0.85", "IV" ],
  [ 430, "flash cannon", "steel", "special", "10", "80", "1", "IV" ],
  [ 431, "rock climb", "normal", "physical", "20", "90", "0.85", "IV" ],
  [ 432, "defog", "flying", "status", "15", "N/A", "N/A", "IV" ],
  [ 433, "trick room", "psychic", "status", "5", "N/A", "N/A", "IV" ],
  [ 434, "draco meteor", "dragon", "special", "5", "130", "0.9", "IV" ],
  [ 435, "discharge", "electric", "special", "15", "80", "1", "IV" ],
  [ 436, "lava plume", "fire", "special", "15", "80", "1", "IV" ],
  [ 437, "leaf storm", "grass", "special", "5", "130", "0.9", "IV" ],
  [ 438, "power whip", "grass", "physical", "10", "120", "0.85", "IV" ],
  [ 439, "rock wrecker", "rock", "physical", "5", "150", "0.9", "IV" ],
  [ 440, "cross poison", "poison", "physical", "20", "70", "1", "IV" ],
  [ 441, "gunk shot", "poison", "physical", "5", "120", "0.8", "IV" ],
  [ 442, "iron head", "steel", "physical", "15", "80", "1", "IV" ],
  [ 443, "magnet bomb", "steel", "physical", "20", "60", "N/A", "IV" ],
  [ 444, "stone edge", "rock", "physical", "5", "100", "0.8", "IV" ],
  [ 445, "captivate", "normal", "status", "20", "N/A", "1", "IV" ],
  [ 446, "stealth rock", "rock", "status", "20", "N/A", "N/A", "IV" ],
  [ 447, "grass knot", "grass", "special", "20", "N/A", "1", "IV" ],
  [ 448, "chatter", "flying", "special", "20", "65", "1", "IV" ],
  [ 449, "judgment", "normal", "special", "10", "100", "1", "IV" ],
  [ 450, "bug bite", "bug", "physical", "20", "60", "1", "IV" ],
  [ 451, "charge beam", "electric", "special", "10", "50", "0.9", "IV" ],
  [ 452, "wood hammer", "grass", "physical", "15", "120", "1", "IV" ],
  [ 453, "aqua jet", "water", "physical", "20", "40", "1", "IV" ],
  [ 454, "attack order", "bug", "physical", "15", "90", "1", "IV" ],
  [ 455, "defend order", "bug", "status", "10", "N/A", "N/A", "IV" ],
  [ 456, "heal order", "bug", "status", "10", "N/A", "N/A", "IV" ],
  [ 457, "head smash", "rock", "physical", "5", "150", "0.8", "IV" ],
  [ 458, "double hit", "normal", "physical", "10", "35", "0.9", "IV" ],
  [ 459, "roar of time", "dragon", "special", "5", "150", "0.9", "IV" ],
  [ 460, "spacial rend", "dragon", "special", "5", "100", "0.95", "IV" ],
  [ 461, "lunar dance", "psychic", "status", "10", "N/A", "N/A", "IV" ],
  [ 462, "crush grip", "normal", "physical", "5", "N/A", "1", "IV" ],
  [ 463, "magma storm", "fire", "special", "5", "100", "0.75", "IV" ],
  [ 464, "dark void", "dark", "status", "10", "N/A", "0.5", "IV" ],
  [ 465, "seed flare", "grass", "special", "5", "120", "0.85", "IV" ],
  [ 466, "ominous wind", "ghost", "special", "5", "60", "1", "IV" ],
  [ 467, "shadow force", "ghost", "physical", "5", "120", "1", "IV" ],
  [ 468, "hone claws", "dark", "status", "15", "N/A", "N/A", "V" ],
  [ 469, "wide guard", "rock", "status", "10", "N/A", "N/A", "V" ],
  [ 470, "guard split", "psychic", "status", "10", "N/A", "N/A", "V" ],
  [ 471, "power split", "psychic", "status", "10", "N/A", "N/A", "V" ],
  [ 472, "wonder room", "psychic", "status", "10", "N/A", "N/A", "V" ],
  [ 473, "psyshock", "psychic", "special", "10", "80", "1", "V" ],
  [ 474, "venoshock", "poison", "special", "10", "65", "1", "V" ],
  [ 475, "autotomize", "steel", "status", "15", "N/A", "N/A", "V" ],
  [ 476, "rage powder", "bug", "status", "20", "N/A", "N/A", "V" ],
  [ 477, "telekinesis", "psychic", "status", "15", "N/A", "N/A", "V" ],
  [ 478, "magic room", "psychic", "status", "10", "N/A", "N/A", "V" ],
  [ 479, "smack down", "rock", "physical", "15", "50", "1", "V" ],
  [ 480, "storm throw", "fighting", "physical", "10", "60", "1", "V" ],
  [ 481, "flame burst", "fire", "special", "15", "70", "1", "V" ],
  [ 482, "sludge wave", "poison", "special", "10", "95", "1", "V" ],
  [ 483, "quiver dance", "bug", "status", "20", "N/A", "N/A", "V" ],
  [ 484, "heavy slam", "steel", "physical", "10", "N/A", "1", "V" ],
  [ 485, "synchronoise", "psychic", "special", "10", "120", "1", "V" ],
  [ 486, "electro ball", "electric", "special", "10", "N/A", "1", "V" ],
  [ 487, "soak", "water", "status", "20", "N/A", "1", "V" ],
  [ 488, "flame charge", "fire", "physical", "20", "50", "1", "V" ],
  [ 489, "coil", "poison", "status", "20", "N/A", "N/A", "V" ],
  [ 490, "low sweep", "fighting", "physical", "20", "65", "1", "V" ],
  [ 491, "acid spray", "poison", "special", "20", "40", "1", "V" ],
  [ 492, "foul play", "dark", "physical", "15", "95", "1", "V" ],
  [ 493, "simple beam", "normal", "status", "15", "N/A", "1", "V" ],
  [ 494, "entrainment", "normal", "status", "15", "N/A", "1", "V" ],
  [ 495, "after you", "normal", "status", "15", "N/A", "N/A", "V" ],
  [ 496, "round", "normal", "special", "15", "60", "1", "V" ],
  [ 497, "echoed voice", "normal", "special", "15", "40", "1", "V" ],
  [ 498, "chip away", "normal", "physical", "20", "70", "1", "V" ],
  [ 499, "clear smog", "poison", "special", "15", "50", "N/A", "V" ],
  [ 500, "stored power", "psychic", "special", "10", "20", "1", "V" ],
  [ 501, "quick guard", "fighting", "status", "15", "N/A", "N/A", "V" ],
  [ 502, "ally switch", "psychic", "status", "15", "N/A", "N/A", "V" ],
  [ 503, "scald", "water", "special", "15", "80", "1", "V" ],
  [ 504, "shell smash", "normal", "status", "15", "N/A", "N/A", "V" ],
  [ 505, "heal pulse", "psychic", "status", "10", "N/A", "N/A", "V" ],
  [ 506, "hex", "ghost", "special", "10", "65", "1", "V" ],
  [ 507, "sky drop", "flying", "physical", "10", "60", "1", "V" ],
  [ 508, "shift gear", "steel", "status", "10", "N/A", "N/A", "V" ],
  [ 509, "circle throw", "fighting", "physical", "10", "60", "0.9", "V" ],
  [ 510, "incinerate", "fire", "special", "15", "60", "1", "V" ],
  [ 511, "quash", "dark", "status", "15", "N/A", "1", "V" ],
  [ 512, "acrobatics", "flying", "physical", "15", "55", "1", "V" ],
  [ 513, "reflect type", "normal", "status", "15", "N/A", "N/A", "V" ],
  [ 514, "retaliate", "normal", "physical", "5", "70", "1", "V" ],
  [ 515, "final gambit", "fighting", "special", "5", "N/A", "1", "V" ],
  [ 516, "bestow", "normal", "status", "15", "N/A", "N/A", "V" ],
  [ 517, "inferno", "fire", "special", "5", "100", "0.5", "V" ],
  [ 518, "water pledge", "water", "special", "10", "80", "1", "V" ],
  [ 519, "fire pledge", "fire", "special", "10", "80", "1", "V" ],
  [ 520, "grass pledge", "grass", "special", "10", "80", "1", "V" ],
  [ 521, "volt switch", "electric", "special", "20", "70", "1", "V" ],
  [ 522, "struggle bug", "bug", "special", "20", "50", "1", "V" ],
  [ 523, "bulldoze", "ground", "physical", "20", "60", "1", "V" ],
  [ 524, "frost breath", "ice", "special", "10", "60", "0.9", "V" ],
  [ 525, "dragon tail", "dragon", "physical", "10", "60", "0.9", "V" ],
  [ 526, "work up", "normal", "status", "30", "N/A", "N/A", "V" ],
  [ 527, "electroweb", "electric", "special", "15", "55", "0.95", "V" ],
  [ 528, "wild charge", "electric", "physical", "15", "90", "1", "V" ],
  [ 529, "drill run", "ground", "physical", "10", "80", "0.95", "V" ],
  [ 530, "dual chop", "dragon", "physical", "15", "40", "0.9", "V" ],
  [ 531, "heart stamp", "psychic", "physical", "25", "60", "1", "V" ],
  [ 532, "horn leech", "grass", "physical", "10", "75", "1", "V" ],
  [ 533, "sacred sword", "fighting", "physical", "15", "90", "1", "V" ],
  [ 534, "razor shell", "water", "physical", "10", "75", "0.95", "V" ],
  [ 535, "heat crash", "fire", "physical", "10", "N/A", "1", "V" ],
  [ 536, "leaf tornado", "grass", "special", "10", "65", "0.9", "V" ],
  [ 537, "steamroller", "bug", "physical", "20", "65", "1", "V" ],
  [ 538, "cotton guard", "grass", "status", "10", "N/A", "N/A", "V" ],
  [ 539, "night daze", "dark", "special", "10", "85", "0.95", "V" ],
  [ 540, "psystrike", "psychic", "special", "10", "100", "1", "V" ],
  [ 541, "tail slap", "normal", "physical", "10", "25", "0.85", "V" ],
  [ 542, "hurricane", "flying", "special", "10", "110", "0.7", "V" ],
  [ 543, "head charge", "normal", "physical", "15", "120", "1", "V" ],
  [ 544, "gear grind", "steel", "physical", "15", "50", "0.85", "V" ],
  [ 545, "searing shot", "fire", "special", "5", "100", "1", "V" ],
  [ 546, "techno blast", "normal", "special", "5", "120", "1", "V" ],
  [ 547, "relic song", "normal", "special", "10", "75", "1", "V" ],
  [ 548, "secret sword", "fighting", "special", "10", "85", "1", "V" ],
  [ 549, "glaciate", "ice", "special", "10", "65", "0.95", "V" ],
  [ 550, "bolt strike", "electric", "physical", "5", "130", "0.85", "V" ],
  [ 551, "blue flare", "fire", "special", "5", "130", "0.85", "V" ],
  [ 552, "fiery dance", "fire", "special", "10", "80", "1", "V" ],
  [ 553, "freeze shock", "ice", "physical", "5", "140", "0.9", "V" ],
  [ 554, "ice burn", "ice", "special", "5", "140", "0.9", "V" ],
  [ 555, "snarl", "dark", "special", "15", "55", "0.95", "V" ],
  [ 556, "icicle crash", "ice", "physical", "10", "85", "0.9", "V" ],
  [ 557, "v-create", "fire", "physical", "5", "180", "0.95", "V" ],
  [ 558, "fusion flare", "fire", "special", "5", "100", "1", "V" ],
  [ 559, "fusion bolt", "electric", "physical", "5", "100", "1", "V" ],
  [ 560, "flying press", "fighting", "physical", "10", "100", "0.95", "VI" ],
  [ 561, "mat block", "fighting", "status", "10", "N/A", "N/A", "VI" ],
  [ 562, "belch", "poison", "special", "10", "120", "0.9", "VI" ],
  [ 563, "rototiller", "ground", "status", "10", "N/A", "N/A", "VI" ],
  [ 564, "sticky web", "bug", "status", "20", "N/A", "N/A", "VI" ],
  [ 565, "fell stinger", "bug", "physical", "25", "50", "1", "VI" ],
  [ 566, "phantom force", "ghost", "physical", "10", "90", "1", "VI" ],
  [ 567, "trick-or-treat", "ghost", "status", "20", "N/A", "1", "VI" ],
  [ 568, "noble roar", "normal", "status", "30", "N/A", "1", "VI" ],
  [ 569, "ion deluge", "electric", "status", "25", "N/A", "N/A", "VI" ],
  [ 570, "parabolic charge", "electric", "special", "20", "65", "1", "VI" ],
  [ 571, "forest's curse", "grass", "status", "20", "N/A", "1", "VI" ],
  [ 572, "petal blizzard", "grass", "physical", "15", "90", "1", "VI" ],
  [ 573, "freeze-dry", "ice", "special", "20", "70", "1", "VI" ],
  [ 574, "disarming voice", "fairy", "special", "15", "40", "N/A", "VI" ],
  [ 575, "parting shot", "dark", "status", "20", "N/A", "1", "VI" ],
  [ 576, "topsy-turvy", "dark", "status", "20", "N/A", "N/A", "VI" ],
  [ 577, "draining kiss", "fairy", "special", "10", "50", "1", "VI" ],
  [ 578, "crafty shield", "fairy", "status", "10", "N/A", "N/A", "VI" ],
  [ 579, "flower shield", "fairy", "status", "10", "N/A", "N/A", "VI" ],
  [ 580, "grassy terrain", "grass", "status", "10", "N/A", "N/A", "VI" ],
  [ 581, "misty terrain", "fairy", "status", "10", "N/A", "N/A", "VI" ],
  [ 582, "electrify", "electric", "status", "20", "N/A", "N/A", "VI" ],
  [ 583, "play rough", "fairy", "physical", "10", "90", "0.9", "VI" ],
  [ 584, "fairy wind", "fairy", "special", "30", "40", "1", "VI" ],
  [ 585, "moonblast", "fairy", "special", "15", "95", "1", "VI" ],
  [ 586, "boomburst", "normal", "special", "10", "140", "1", "VI" ],
  [ 587, "fairy lock", "fairy", "status", "10", "N/A", "N/A", "VI" ],
  [ 588, "king's shield", "steel", "status", "10", "N/A", "N/A", "VI" ],
  [ 589, "play nice", "normal", "status", "20", "N/A", "N/A", "VI" ],
  [ 590, "confide", "normal", "status", "20", "N/A", "N/A", "VI" ],
  [ 591, "diamond storm", "rock", "physical", "5", "100", "0.95", "VI" ],
  [ 592, "steam eruption", "water", "special", "5", "110", "0.95", "VI" ],
  [ 593, "hyperspace hole", "psychic", "special", "5", "80", "N/A", "VI" ],
  [ 594, "water shuriken", "water", "special", "20", "15", "1", "VI" ],
  [ 595, "mystical fire", "fire", "special", "10", "75", "1", "VI" ],
  [ 596, "spiky shield", "grass", "status", "10", "N/A", "N/A", "VI" ],
  [ 597, "aromatic mist", "fairy", "status", "20", "N/A", "N/A", "VI" ],
  [ 598, "eerie impulse", "electric", "status", "15", "N/A", "1", "VI" ],
  [ 599, "venom drench", "poison", "status", "20", "N/A", "1", "VI" ],
  [ 600, "powder", "bug", "status", "20", "N/A", "1", "VI" ],
  [ 601, "geomancy", "fairy", "status", "10", "N/A", "N/A", "VI" ],
  [ 602, "magnetic flux", "electric", "status", "20", "N/A", "N/A", "VI" ],
  [ 603, "happy hour", "normal", "status", "30", "N/A", "N/A", "VI" ],
  [ 604, "electric terrain", "electric", "status", "10", "N/A", "N/A", "VI" ],
  [ 605, "dazzling gleam", "fairy", "special", "10", "80", "1", "VI" ],
  [ 606, "celebrate", "normal", "status", "40", "N/A", "N/A", "VI" ],
  [ 607, "hold hands", "normal", "status", "40", "N/A", "N/A", "VI" ],
  [ 608, "baby-doll eyes", "fairy", "status", "30", "N/A", "1", "VI" ],
  [ 609, "nuzzle", "electric", "physical", "20", "20", "1", "VI" ],
  [ 610, "hold back", "normal", "physical", "40", "40", "1", "VI" ],
  [ 611, "infestation", "bug", "special", "20", "20", "1", "VI" ],
  [ 612, "power-up punch", "fighting", "physical", "20", "40", "1", "VI" ],
  [ 613, "oblivion wing", "flying", "special", "10", "80", "1", "VI" ],
  [ 614, "thousand arrows", "ground", "physical", "10", "90", "1", "VI" ],
  [ 615, "thousand waves", "ground", "physical", "10", "90", "1", "VI" ],
  [ 616, "land's wrath", "ground", "physical", "10", "90", "1", "VI" ],
  [ 617, "light of ruin", "fairy", "special", "5", "140", "0.9", "VI" ],
  [ 618, "origin pulse", "water", "special", "10", "110", "0.85", "VI" ],
  [ 619, "precipice blades", "ground", "physical", "10", "120", "0.85", "VI" ],
  [ 620, "dragon ascent", "flying", "physical", "5", "120", "1", "VI" ],
  [ 621, "hyperspace fury", "dark", "physical", "5", "100", "N/A", "VI" ],
  [ 622, "breakneck blitz", "normal", "physical", "1", "N/A", "N/A", "VII" ],
  [ 623, "breakneck blitz", "normal", "special", "1", "N/A", "N/A", "VII" ],
  [ 624, "all-out pummeling", "fighting", "physical", "1", "N/A", "N/A", "VII" ],
  [ 625, "all-out pummeling", "fighting", "special", "1", "N/A", "N/A", "VII" ],
  [ 626, "supersonic skystrike", "flying", "physical", "1", "N/A", "N/A", "VII" ],
  [ 627, "supersonic skystrike", "flying", "special", "1", "N/A", "N/A", "VII" ],
  [ 628, "acid downpour", "poison", "physical", "1", "N/A", "N/A", "VII" ],
  [ 629, "acid downpour", "poison", "special", "1", "N/A", "N/A", "VII" ],
  [ 630, "tectonic rage", "ground", "physical", "1", "N/A", "N/A", "VII" ],
  [ 631, "tectonic rage", "ground", "special", "1", "N/A", "N/A", "VII" ],
  [ 632, "continental crush", "rock", "physical", "1", "N/A", "N/A", "VII" ],
  [ 633, "continental crush", "rock", "special", "1", "N/A", "N/A", "VII" ],
  [ 634, "savage spin-out", "bug", "physical", "1", "N/A", "N/A", "VII" ],
  [ 635, "savage spin-out", "bug", "special", "1", "N/A", "N/A", "VII" ],
  [ 636, "never-ending nightmare", "ghost", "physical", "1", "N/A", "N/A", "VII" ],
  [ 637, "never-ending nightmare", "ghost", "special", "1", "N/A", "N/A", "VII" ],
  [ 638, "corkscrew crash", "steel", "physical", "1", "N/A", "N/A", "VII" ],
  [ 639, "corkscrew crash", "steel", "special", "1", "N/A", "N/A", "VII" ],
  [ 640, "inferno overdrive", "fire", "physical", "1", "N/A", "N/A", "VII" ],
  [ 641, "inferno overdrive", "fire", "special", "1", "N/A", "N/A", "VII" ],
  [ 642, "hydro vortex", "water", "physical", "1", "N/A", "N/A", "VII" ],
  [ 643, "hydro vortex", "water", "special", "1", "N/A", "N/A", "VII" ],
  [ 644, "bloom doom", "grass", "physical", "1", "N/A", "N/A", "VII" ],
  [ 645, "bloom doom", "grass", "special", "1", "N/A", "N/A", "VII" ],
  [ 646, "gigavolt havoc", "electric", "physical", "1", "N/A", "N/A", "VII" ],
  [ 647, "gigavolt havoc", "electric", "special", "1", "N/A", "N/A", "VII" ],
  [ 648, "shattered psyche", "psychic", "physical", "1", "N/A", "N/A", "VII" ],
  [ 649, "shattered psyche", "psychic", "special", "1", "N/A", "N/A", "VII" ],
  [ 650, "subzero slammer", "ice", "physical", "1", "N/A", "N/A", "VII" ],
  [ 651, "subzero slammer", "ice", "special", "1", "N/A", "N/A", "VII" ],
  [ 652, "devastating drake", "dragon", "physical", "1", "N/A", "N/A", "VII" ],
  [ 653, "devastating drake", "dragon", "special", "1", "N/A", "N/A", "VII" ],
  [ 654, "black hole eclipse", "dark", "physical", "1", "N/A", "N/A", "VII" ],
  [ 655, "black hole eclipse", "dark", "special", "1", "N/A", "N/A", "VII" ],
  [ 656, "twinkle tackle", "fairy", "physical", "1", "N/A", "N/A", "VII" ],
  [ 657, "twinkle tackle", "fairy", "special", "1", "N/A", "N/A", "VII" ],
  [ 658, "catastropika", "electric", "physical", "1", "210", "N/A", "VII" ],
  [ 659, "shore up", "ground", "status", "10", "N/A", "N/A", "VII" ],
  [ 660, "first impression", "bug", "physical", "10", "90", "1", "VII" ],
  [ 661, "baneful bunker", "poison", "status", "10", "N/A", "N/A", "VII" ],
  [ 662, "spirit shackle", "ghost", "physical", "10", "80", "1", "VII" ],
  [ 663, "darkest lariat", "dark", "physical", "10", "85", "1", "VII" ],
  [ 664, "sparkling aria", "water", "special", "10", "90", "1", "VII" ],
  [ 665, "ice hammer", "ice", "physical", "10", "100", "0.9", "VII" ],
  [ 666, "floral healing", "fairy", "status", "10", "N/A", "N/A", "VII" ],
  [ 667, "high horsepower", "ground", "physical", "10", "95", "0.95", "VII" ],
  [ 668, "strength sap", "grass", "status", "10", "N/A", "1", "VII" ],
  [ 669, "solar blade", "grass", "physical", "10", "125", "1", "VII" ],
  [ 670, "leafage", "grass", "physical", "40", "40", "1", "VII" ],
  [ 671, "spotlight", "normal", "status", "15", "N/A", "N/A", "VII" ],
  [ 672, "toxic thread", "poison", "status", "20", "N/A", "1", "VII" ],
  [ 673, "laser focus", "normal", "status", "30", "N/A", "N/A", "VII" ],
  [ 674, "gear up", "steel", "status", "20", "N/A", "N/A", "VII" ],
  [ 675, "throat chop", "dark", "physical", "15", "80", "1", "VII" ],
  [ 676, "pollen puff", "bug", "special", "15", "90", "1", "VII" ],
  [ 677, "anchor shot", "steel", "physical", "20", "80", "1", "VII" ],
  [ 678, "psychic terrain", "psychic", "status", "10", "N/A", "N/A", "VII" ],
  [ 679, "lunge", "bug", "physical", "15", "80", "1", "VII" ],
  [ 680, "fire lash", "fire", "physical", "15", "80", "1", "VII" ],
  [ 681, "power trip", "dark", "physical", "10", "20", "1", "VII" ],
  [ 682, "burn up", "fire", "special", "5", "130", "1", "VII" ],
  [ 683, "speed swap", "psychic", "status", "10", "N/A", "N/A", "VII" ],
  [ 684, "smart strike", "steel", "physical", "10", "70", "N/A", "VII" ],
  [ 685, "purify", "poison", "status", "20", "N/A", "N/A", "VII" ],
  [ 686, "revelation dance", "normal", "special", "15", "90", "1", "VII" ],
  [ 687, "core enforcer", "dragon", "special", "10", "100", "1", "VII" ],
  [ 688, "trop kick", "grass", "physical", "15", "70", "1", "VII" ],
  [ 689, "instruct", "psychic", "status", "15", "N/A", "N/A", "VII" ],
  [ 690, "beak blast", "flying", "physical", "15", "100", "1", "VII" ],
  [ 691, "clanging scales", "dragon", "special", "5", "110", "1", "VII" ],
  [ 692, "dragon hammer", "dragon", "physical", "15", "90", "1", "VII" ],
  [ 693, "brutal swing", "dark", "physical", "20", "60", "1", "VII" ],
  [ 694, "aurora veil", "ice", "status", "20", "N/A", "N/A", "VII" ],
  [ 695, "sinister arrow raid", "ghost", "physical", "1", "180", "N/A", "VII" ],
  [ 696, "malicious moonsault", "dark", "physical", "1", "180", "N/A", "VII" ],
  [ 697, "oceanic operetta", "water", "special", "1", "195", "N/A", "VII" ],
  [ 698, "guardian of alola", "fairy", "special", "1", "N/A", "N/A", "VII" ],
  [ 699, "soul-stealing 7-star strike", "ghost", "physical", "1", "195", "N/A", "VII" ],
  [ 700, "stoked sparksurfer", "electric", "special", "1", "175", "N/A", "VII" ],
  [ 701, "pulverizing pancake", "normal", "physical", "1", "210", "N/A", "VII" ],
  [ 702, "extreme evoboost", "normal", "status", "1", "N/A", "N/A", "VII" ],
  [ 703, "genesis supernova", "psychic", "special", "1", "185", "N/A", "VII" ],
  [ 704, "shell trap", "fire", "special", "5", "150", "1", "VII" ],
  [ 705, "fleur cannon", "fairy", "special", "5", "130", "0.9", "VII" ],
  [ 706, "psychic fangs", "psychic", "physical", "10", "85", "1", "VII" ],
  [ 707, "stomping tantrum", "ground", "physical", "10", "75", "1", "VII" ],
  [ 708, "shadow bone", "ghost", "physical", "10", "85", "1", "VII" ],
  [ 709, "accelerock", "rock", "physical", "20", "40", "1", "VII" ],
  [ 710, "liquidation", "water", "physical", "10", "85", "1", "VII" ],
  [ 711, "prismatic laser", "psychic", "special", "10", "160", "1", "VII" ],
  [ 712, "spectral thief", "ghost", "physical", "10", "90", "1", "VII" ],
  [ 713, "sunsteel strike", "steel", "physical", "5", "100", "1", "VII" ],
  [ 714, "moongeist beam", "ghost", "special", "5", "100", "1", "VII" ],
  [ 715, "tearful look", "normal", "status", "20", "N/A", "N/A", "VII" ],
  [ 716, "zing zap", "electric", "physical", "10", "80", "1", "VII" ],
  [ 717, "nature's madness", "fairy", "special", "10", "N/A", "0.9", "VII" ],
  [ 718, "multi-attack", "normal", "physical", "10", "90", "1", "VII" ],
  [ 719, "10,000,000 volt thunderbolt", "electric", "special", "1", "195", "N/A", "VII" ],
  [ 720, "mind blown", "fire", "special", "5", "150", "1", "VII" ],
  [ 721, "plasma fists", "electric", "physical", "15", "100", "1", "VII" ],
  [ 722, "photon geyser", "psychic", "special", "5", "100", "1", "VII" ],
  [ 723, "light that burns the sky", "psychic", "special", "1", "200", "N/A", "VII" ],
  [ 724, "searing sunraze smash", "steel", "special", "1", "200", "N/A", "VII" ],
  [ 725, "menacing moonraze maelstrom", "ghost", "special", "1", "200", "N/A", "VII" ],
  [ 726, "let's snuggle forever", "fairy", "physical", "1", "190", "N/A", "VII" ],
  [ 727, "splintered stormshards", "rock", "physical", "1", "190", "N/A", "VII" ],
  [ 728, "clangorous soulblaze", "dragon", "special", "1", "185", "N/A", "VII" ],
  [ 729, "zippy zap", "electric", "physical", "15", "50", "1", "VII" ],
  [ 730, "splishy splash", "water", "special", "15", "90", "1", "VII" ],
  [ 731, "floaty fall", "flying", "physical", "15", "90", "0.95", "VII" ],
  [ 732, "pika papow", "electric", "special", "20", "N/A", "N/A", "VII" ],
  [ 733, "bouncy bubble", "water", "special", "15", "90", "1", "VII" ],
  [ 734, "buzzy buzz", "electric", "special", "15", "90", "1", "VII" ],
  [ 735, "sizzly slide", "fire", "physical", "15", "90", "1", "VII" ],
  [ 736, "glitzy glow", "psychic", "special", "15", "90", "1", "VII" ],
  [ 737, "baddy bad", "dark", "special", "15", "90", "1", "VII" ],
  [ 738, "sappy seed", "grass", "physical", "15", "90", "1", "VII" ],
  [ 739, "freezy frost", "ice", "special", "15", "90", "1", "VII" ],
  [ 740, "sparkly swirl", "fairy", "special", "15", "90", "1", "VII" ],
  [ 741, "veevee volley", "normal", "physical", "20", "N/A", "N/A", "VII" ],
  [ 742, "double iron bash", "steel", "physical", "5", "60", "1", "VII" ]
]

move_list.each do |mdIndex, mdName, mdType, mdCategory, mdPP, mdPower, mdAccuracy, mdGeneration|
  Move.create( index_number: mdIndex, move_name: mdName, move_type: mdType, category: mdCategory, pp: mdPP, power: mdPower, accuracy: mdAccuracy, generation: mdGeneration )
end